### ISSUE TITLE
如何将滚动显示变为分页？

### ISSUE THREAD

**Issue by SNOWandwhite** [xtreme1-io/xtreme1#101]
我在整个文档中发现，滚动功能属于自定义封装，现在像将其改为分页，请问怎样做？
（我在其他文件中发现了分页功能的代码，但存在bug）

**Comment by raincolor** [comment]
现在开源版本卡片类页面仅支持滚动分页。想替换为分页条分页功能（目前我们只有表格类页面做了分页条分页），可以把需要分页的元素外层的滚动分页组件ScrollContainer删掉，引入我们自定义的分页组件 xtreme1\frontend\main\src\components\Table\src\ThePagination.vue 即可，或者你也可以自己封装或引入三方库分页组件

**Comment by raincolor** [comment]
Currently, card pages in the open source version only support scrolling pagination. If you want to replace it with paging bar paging function (currently we only have paging bar paging for table type pages), you can delete the scrolling paging component ScrollContainer on the outer layer of the element that needs paging, and introduce our custom paging component 'xtreme1\frontend\main \src\components\Table\src\ThePagination.vue' is enough, or you can also encapsulate or import the third-party library pagination component yourself

**Comment by SNOWandwhite** [comment]
> 现在开源版本卡片类页面仅支持滚动分页。想替换为分页条分页功能（目前我们只有表格类页面做了分页条分页），可以把需要分页的元素外层的滚动分页组件ScrollContainer删掉，引入我们自定义的分页组件 xtreme1\frontend\main\src\components\Table\src\ThePagination.vue 即可，或者你也可以自己封装或引入三方库分页组件

首先，感谢您的答疑，我现在将ScrollContainer标签删除后，使用您所说的Vue标签，但现在数据页面什么都不显示了。。。

**Comment by SNOWandwhite** [comment]
<ThePagination>
            <ImgCard
              v-for="i in list"
              :key="i.id"
              :object="objectMap[i.id]"
              @handleSelected="handleSelected"
              :showAnnotation="showAnnotation"
              :isSelected="selectedList.filter((item) => item === i.id).length > 0"
              :data="i"
              :info="info"
              :type="type"
              @handleDelete="handleDeleteSingle"
              @handleSingleAnnotate="handleSingleAnnotate"
              @handleAnotateFrame="handleAnotateFrame"
            />
          </ThePagination>
就像这样，但是它并没有显示图像

**Comment by SNOWandwhite** [comment]
ThePagination
            ImgCard
/ThePagination
就像这样，但是它什么都没有显示在web界面上

**Comment by raincolor** [comment]
After introducing the corresponding paging component bar, you need to do some other things, such as passing in the corresponding props

**Comment by SNOWandwhite** [comment]
> 

我正在对其进行尝试，希望能够成功
