### ISSUE TITLE
关于相机内外参数的问题

### ISSUE THREAD

**Issue by SNOWandwhite** [xtreme1-io/xtreme1#102]
通过xtreme1加载nussence数据集后，在点云上标注的方框与左侧2D图像出现偏差。请问，应该怎样解决？nussence的相机内外参数已经写好了，并没有使用xtreme1的默认相机参数。

**Comment by may0908** [comment]
您好，请问您方便发一个样例数据看一下吗？

**Comment by SNOWandwhite** [comment]
抱歉，数据暂时无法上传，能否问一下，在前端显示过程中，前端对相机的内外参数进行了什么样的操作码？例如转置、逆运算等

**Comment by SNOWandwhite** [comment]
> 您好，请问您方便发一个样例数据看一下吗？
抱歉，数据暂时无法上传，能否问一下，在前端显示过程中，前端对相机的内外参数进行了什么样的操作码？例如转置、逆运算等

**Comment by may0908** [comment]
Hi, we don't do any operation to the parameters. How about send your sample data here->may@basic.ai, and we will solve the problem for you.

**Comment by SNOWandwhite** [comment]
> Hi, we don't do any operation to the parameters. How about send your sample data here->[may@basic.ai](mailto:may@basic.ai), and we will solve the problem for you.

I'm sorry about long time reply, I just solved this problem. Because of my mistake, the params of camera are saved in wrong way!
