### ISSUE TITLE
Enter the annotation interface，Model call failure

### ISSUE THREAD

**Issue by hdcdicdscj** [xtreme1-io/xtreme1#103]
![image](https://user-images.githubusercontent.com/129840837/230270578-f8ee9fd3-7426-482c-a8f1-6dafd40905ee.png)

**Comment by jaggerwang** [comment]
Please supply more info, like web console logs, container logs etc.

**Comment by nicozhan** [comment]
## Enable model services
Make sure you have installed [NVIDIA Driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html) and [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker). But you do not need to install the CUDA Toolkit, as it already contained in the model image.

### You need set "default-runtime" as "nvidia" in /etc/docker/daemon.json and restart docker to enable NVIDIA Container Toolkit
```{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  },
  "default-runtime": "nvidia"
}
```

For more info, [see docs](https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker#enable-model-services)
