### ISSUE TITLE
The record of failure to models page by clicking run model should have a delete button.

### ISSUE THREAD

**Issue by hdcdicdscj** [xtreme1-io/xtreme1#104]
![image](https://user-images.githubusercontent.com/129840837/230270843-c4c1db0f-0884-4e03-bfe9-4637a6a8917f.png)

**Comment by nicozhan** [comment]
Thanks for your suggestion. I will be added with the next update.

**Comment by raincolor** [comment]
the issue has been resolved, you can try again
