### ISSUE TITLE
Install Xtreme1 on a Mac with Apple silicon

### ISSUE THREAD

**Issue by kcy-sudo** [xtreme1-io/xtreme1#105]
My computer is a MacBook Air with Apple silicon/M1 Preview, I encountered several issues when installing Xtreme1. I will share them here.
1. Download  Docker Desktop for Mac with Apple silicon
[https://docs.docker.com/desktop/install/mac-install/](https://docs.docker.com/desktop/install/mac-install/)

2. Docker desktop for Mac does not want to start
![image](https://user-images.githubusercontent.com/54022738/230530610-e0030317-6260-4fd2-af8a-a7a42d1b3cf1.png)
--remove files
$ rm -rf ~/Library/Containers/com.docker.*
--modify configuration 
 $ vi ~/Library/Group Containers/group.com.docker/settings.json
--find` "filesharingDirectories"` and change into `"filesharingDirectories": []`

3. Docker (Apple Silicon/M1 Preview) MySQL "no matching manifest for Linux/arm64/v8 in the manifest list entries"
    <img width="426" alt="image" src="https://user-images.githubusercontent.com/54022738/230531846-47496cbf-28d4-4ebb-88c6-0b3f3a6dcaaf.png">
    Oracle maintains a MySQL 8.0.23 docker image for arm64. Use it in your docker-compose file

**Comment by nicozhan** [comment]
Hi [kcy-sudo](https://github.com/kcy-sudo)!

[Please check Issue #96 ]

[Running docker images on ARM architecture machines](https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker#running-docker-images-on-arm-architecture-machines)
​⚠ Please note that certain Docker images, including MySQL, may not be compatible with the ARM architecture. In case your computer is based on an ARM CPU (e.g. Apple M1), you can create a Docker Compose override file called docker-compose.override.yml and include the following content. While this method uses QEMU emulation to enforce the use of the ARM64 image on the ARM64 platform, it may impact performance.

```
services:
  mysql:
    platform: linux/amd64
```
