### ISSUE TITLE
How do I extend the iconfont configuration in a project

### ISSUE THREAD

**Issue by AzronChan** [xtreme1-io/xtreme1#108]
I need to use the new icon.But do not know to add the new icon to the current iconfont file,One way is for you to grant permission to the iconfont project so that I can copy the project and add new ICONS,

**Comment by AzronChan** [comment]
我需要使用新的图标。但是不知道如何将新的图标添加到当前的iconfont文件中，一种方法是为您授予iconfont项目的权限，这样我就可以复制项目并添加新的图标。

**Comment by raincolor** [comment]
Sorry, the icon library we are currently using does not support custom extension icons. You can choose suitable icons from https://icones.netlify.app/collection/all. If you want to use your own icons, you can add a new iconfont library to the project and use your own icons. Alternatively, for small amounts of usage, you can use SVG in the project. After adding the xxx.svg file under \xtreme1\frontend\main\src\assets\icons, you can use <SvgIcon name='xxx'> in the component.
