### ISSUE TITLE
Hi, when I click on the help document, it does not pop up a new page but replaces the current page, which is very inconvenient for me. Can you separate the pages of the help document?

### ISSUE THREAD

**Issue by sunrise93** [xtreme1-io/xtreme1#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicozhan** [comment]
Ok. We can fix in with the next update.

**Comment by nicozhan** [comment]
#114
