### ISSUE TITLE
有关于pc-tool中的Box设置

### ISSUE THREAD

**Issue by SNOWandwhite** [xtreme1-io/xtreme1#119]
问题1：我想问一下在Box.ts当中的positions中参数的含义，虽然其中标明了，z, -z，我想知道更加详细的参数设置
问题2：当我根据positions进行PlaneBufferGeometry和Mesh进行2D矩形的绘制时，发现只绘制出了一个三角形

**Comment by guhaomine** [comment]
positions指的是一个box中包含8个顶点坐标以及箭头坐标，每3个一组表示一个顶点xyz值，indices中每两个一组表示一条线段在positions数组中起始位置的索引，lineDistance存储每个顶点到下一个顶点的距离,可参照threejs文档。  问题2可能就是这些参数没有设置准确。

**Comment by SNOWandwhite** [comment]
> positions指的是一个box中包含8个顶点坐标以及箭头坐标，每3个一组表示一个顶点xyz值，indices中每两个一组表示一条线段在positions数组中起始位置的索引，lineDistance存储每个顶点到下一个顶点的距离,可参照threejs文档。 问题2可能就是这些参数没有设置准确。

另外一个问题是，从模型当中所得到的center3D、size3D、rotate3D与这几个参数是如何计算出来的？

**Comment by guhaomine** [comment]
center3D：对于框的中心点坐标，
size3D：让车头指向x轴方向，x，y，z分别对应框在x、y、z三个方向上的长度，也就是车（或其它对象）的长、宽、高
rotation3D：是x轴的朝向旋转到车头真实朝向的欧拉角，一般情况下，框只沿着地面旋转（也就是绕z轴旋转），其x、y旋转分量为0。
以上都位于点云坐标系下。

**Comment by SNOWandwhite** [comment]
> center3D：对于框的中心点坐标， size3D：让车头指向x轴方向，x，y，z分别对应框在x、y、z三个方向上的长度，也就是车（或其它对象）的长、宽、高 rotation3D：是x轴的朝向旋转到车头真实朝向的欧拉角，一般情况下，框只沿着地面旋转（也就是绕z轴旋转），其x、y旋转分量为0。 以上都位于点云坐标系下。

ok。我已经调试完毕了，感谢帮助
