### ISSUE TITLE
未修改的标注框，在导出时，类别丢失，以及导出的标注数据没有classId属性

### ISSUE THREAD

**Issue by lihui-colin** [xtreme1-io/xtreme1#123]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fanyinbo** [comment]
该问题在V0.7.1版本已修复，更新最新版本进行查看
