### ISSUE TITLE
点云显示时，选择强度， 会不显示

### ISSUE THREAD

**Issue by lihui-colin** [xtreme1-io/xtreme1#124]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guhaomine** [comment]
不显示的原因是强度不符合工具显示规范，支持强度0-255值，现在做了兼容支持0-1，你可以更新到最新版本看是否还存在问题，否则检查pcd是否符合要求
