### ISSUE TITLE
How to specify the model to load during the docker installation?

### ISSUE THREAD

**Issue by HuangKaibo2017** [xtreme1-io/xtreme1#126]
Question 1:
In the section "Enable model services", there is no detail model service guidance, only about gpu card enable. 

Question 2:
There is no in WSL2(Ubuntu 20.04 LTS)

Question 3: 
I also found the command "docker compose --profile model up", but I only need image detection model. How can I specify that?

**Comment by HuangKaibo2017** [comment]
Additional info:
1. Ran "docker compose --profile model up" got this information: 
[+] Running 0/2
 ⠋ Container download-image-object-detection-1  Creating                                                           0.1s
 ⠋ Container download-nginx-1                   Creating                                                           0.1s
Error response from daemon: unknown or invalid runtime name: nvidia

The daeman.json was added to /etc/docker/ path manually. Content of daeman.json is the same as installation guide.

2. Ran "nvidia-smi" got following information:

Sun May 21 12:01:32 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.46                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060 w...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8                4W /  N/A|     32MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        22      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        25      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        33      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+

3. cuda driver installed successfully as "https://developer.nvidia.com/cuda/wsl" told.

4. Ran "docker run -it --gpus=all --rm nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -benchmark" got the following info:
 
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Turing" with compute capability 7.5

> Compute 7.5 CUDA device: [NVIDIA GeForce RTX 2060 with Max-Q Design]
30720 bodies, total time for 10 iterations: 68.697 ms
= 137.375 billion interactions per second
= 2747.496 single-precision GFLOP/s at 20 flops per interaction

**Comment by jaggerwang** [comment]
Question 1 & Question 3:
To enable model services, you just need to add option `--profile model` when run docker compose. If you want to enable each model service separately, you can change the profiles of each model service in `docker-compose.yml` to different ones.

Question 2:
As Nvidia driver does not support WSL, so model services cannot run in this environment.
