### ISSUE TITLE
"Model Run Error" when trying to annotate

### ISSUE THREAD

**Issue by boazMgm** [xtreme1-io/xtreme1#127]
Hi,
I'm facing this error  (image attached) when trying to annotate a specific scene:
![image](https://github.com/xtreme1-io/xtreme1/assets/89138398/0ce01257-0585-4893-9d84-8fecdc4c0ab7)

do you know what may cause such error?
Thanks

**Comment by nicozhan** [comment]
Hi [boazMgm](https://github.com/boazMgm)!

1. Make sure you have [Installed model](https://docs.xtreme1.io/xtreme1-docs/get-started/quick-start#install-built-in-models);
2. Check the docs if you are [Running docker images on ARM architecture machines](https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker#running-docker-images-on-arm-architecture-machines);
3. Check the docs to [Enable model services](https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker#enable-model-services) 
4. Set `default-runtime` as `nvidia` in `/etc/docker/daemon.json` and restart docker to enable NVIDIA Container Toolkit 
```{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  },
  "default-runtime": "nvidia"
}
```
5. See issue #96 if you are using OSX MacBook M1/M2 chipset.

**Comment by boazMgm** [comment]
Hi,
Thanks for the quick reply.
We are facing now the following issue as depicted in the figure:
![image](https://github.com/xtreme1-io/xtreme1/assets/89138398/e574ed4b-4ba0-4418-8849-cf4f21003e24)

our application required to exist on a stand alone computer without any internet connection.
Do you have any solution?
Thanks a lot,
Boaz

**Comment by jaggerwang** [comment]
It seems that you cannot pull images from Docker Hub, you can try to pull other images in Docker Hub to test your local network.

**Comment by boazMgm** [comment]
Hi,
it looks like all the containers are up and running:
![image](https://github.com/xtreme1-io/xtreme1/assets/89138398/64b1a841-c1c6-4889-814d-71a2f68aadb1)
![image](https://github.com/xtreme1-io/xtreme1/assets/89138398/66d800a6-b3c1-4727-b271-c37764ef85b7)
Anything else might be the problem?
Thanks

**Comment by boazMgm** [comment]
The big question from our perspective is the Lidar detection model running remotely in your server or is it locally on our pc?
If it's locally we don't understand why there is a proxy issue...

Thanks

**Comment by nicozhan** [comment]
It runs on your local pc.
The engineer can help you on Monday~

**Comment by jaggerwang** [comment]
@boazMgm Of course the models will be running on your local computer, not on our servers. As we said before, the error shows that you failed to pull model images from Docker Hub to your local computer. You can try the follwing command to manually pull model images from Docker Hub to make sure there is no network error between you and Docker Hub.

```
docker pull basicai/xtreme1-point-cloud-object-detection
docker pull basicai/xtreme1-image-object-detection
```

**Comment by nicozhan** [comment]
If you need help, DM me in Slack channel

**Comment by boazMgm** [comment]
Hi,
we have made some progress but currently we run into new issue:
![MicrosoftTeams-image (3)](https://github.com/xtreme1-io/xtreme1/assets/89138398/3b31387f-09e7-4ac1-95c9-a13f3f3118d0)
do you know what may be the issue?
Thanks

**Comment by jaggerwang** [comment]
Is seems that there have some problems of your docker network. You can execute `docker compose down -v` to clean your local installation first and try to install again, be careful this command will remove all volumes, and you will lost all your data. For more advance docs, you can move into [Install with Docker](https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker).
