### ISSUE TITLE
Camera parameters distortion input?

### ISSUE THREAD

**Issue by Nick-Yen** [xtreme1-io/xtreme1#128]
I have distorted parameters in my camera correction parameters
I want to know where to input distorted parameters?

**Comment by nicozhan** [comment]
Hi @Nick-Yen !
Currenltly, this is something we don't supported.
But it is under development and it will be coming soon!

**Comment by nicozhan** [comment]
[On the cloud version](https://app.basic.ai/), you can configue it via following:
1. [Camera Calibration Theory](https://euratom-software.github.io/calcam/html/intro_theory.html#camera-calibration-theory)
2. Json format and description:
```[
    {
        "camera_internal": { // internal reference of the camera
            "fx": 382.06535583,
            "cx": 326.66902661,
            "fy": 421.05123478,
            "cy": 254.70249315
        },
        "camera_external": [ // extrinsics of the camera
            0.76866726,
            0.04361939,
            0.63815985,
            -1.59,
            -0.63870827,
            -0.00174367,
            0.76944701,
            0.91,
            0.03467555,
            -0.9990467,
            0.02651976,
            0.96,
            0,
            0,
            0,
            1
        ],
        "distortionK": [ // Distortion parameter K. Delete this field if you don't have it.
            -0.30912646651268,
            0.0669714063405991
        ],
        "distortionP": [// Distortion parameter P. Delete this field if you don't have it.
            0.00262697599828243,
            0.00106896553188562
        ],
        "distortionInvP": [// Distortion InvP. Delete this field if you don't have it.
            800.836,
            515.212,
            -36.9548,
            39.5822,
            85.4095,
            -23.9415,
            -40.625,
            32.0152,
            37.9534,
            9.22325
        ],
        "width": 1920, // Image width (optional)
        "height": 1280, // Image height (optional)
        "rowMajor": true // Whether the camera extrinsic parameter is line order (default is false)
    },
    ...
]

**Comment by Nick-Yen** [comment]
> [On the cloud version](https://app.basic.ai/), you can configue it via following:
> 
> 1. [Camera Calibration Theory](https://euratom-software.github.io/calcam/html/intro_theory.html#camera-calibration-theory)
> 2. Json format and description:
> 
> ```
>     {
>         "camera_internal": { // internal reference of the camera
>             "fx": 382.06535583,
>             "cx": 326.66902661,
>             "fy": 421.05123478,
>             "cy": 254.70249315
>         },
>         "camera_external": [ // extrinsics of the camera
>             0.76866726,
>             0.04361939,
>             0.63815985,
>             -1.59,
>             -0.63870827,
>             -0.00174367,
>             0.76944701,
>             0.91,
>             0.03467555,
>             -0.9990467,
>             0.02651976,
>             0.96,
>             0,
>             0,
>             0,
>             1
>         ],
>         "distortionK": [ // Distortion parameter K. Delete this field if you don't have it.
>             -0.30912646651268,
>             0.0669714063405991
>         ],
>         "distortionP": [// Distortion parameter P. Delete this field if you don't have it.
>             0.00262697599828243,
>             0.00106896553188562
>         ],
>         "distortionInvP": [// Distortion InvP. Delete this field if you don't have it.
>             800.836,
>             515.212,
>             -36.9548,
>             39.5822,
>             85.4095,
>             -23.9415,
>             -40.625,
>             32.0152,
>             37.9534,
>             9.22325
>         ],
>         "width": 1920, // Image width (optional)
>         "height": 1280, // Image height (optional)
>         "rowMajor": true // Whether the camera extrinsic parameter is line order (default is false)
>     },
>     ...
> ]
> ```
My Distortion parameter K has reached K3, should I directly load the json list mentioned above to len3 and fill it or not yet? Thank you

**Comment by nicozhan** [comment]
Please fill in all `k` in `distortionK`. 
If you don't have the `p`, there is no need to fill in `distortionP`.

**Comment by Nick-Yen** [comment]
> Please fill in all `k` in `distortionK`. If you don't have the `p`, there is no need to fill in `distortionP`.
> 
> `distortionK` can contain multiple values, such as more than 2.

OK Thanks.
