### ISSUE TITLE
Installation without Docker

### ISSUE THREAD

**Issue by mehfuzz** [xtreme1-io/xtreme1#131]
Is there a way to install it locally without using Docker? Both the methods mentioned on the website use Docker to install, but is there a way to install it without using Docker?

**Comment by nicozhan** [comment]
You can try online version https://app.basic.ai/#/login 
It is free to use with the basic plan.

**Comment by mehfuzz** [comment]
I've tried the online version, but I'd like to install and use it locally.

**Comment by nicozhan** [comment]
We don't have a tutorial for now.
If you don't use Docker, the installation will be more complicated.
