### ISSUE TITLE
模型有没有cpu模式得

### ISSUE THREAD

**Issue by zhou1591** [xtreme1-io/xtreme1#132]
想本地部署  gpu 服务器太贵了奥  对小开发团队来说 成本有点高  有cpu 版本 镜像吗

**Comment by nicozhan** [comment]
如果用到预识和交互式模型确实需要GPU服务器。Xtreme1的标注工具是不需要GPU的。

GPU servers are required if pre-labeling and interactive model functions are used. 
Xtreme1's annotation tool does not require a GPU.

**Comment by zhou1591** [comment]
> 如果用到预识和交互式模型确实需要GPU服务器。Xtreme1的标注工具是不需要GPU的。
> 
> GPU servers are required if pre-labeling and interactive model functions are used. Xtreme1's annotation tool does not require a GPU.

是说模型 必须要gpu 吗  或者大佬你知道有什么其他开源的cpu 的点云模型吗

**Comment by nicozhan** [comment]
目前都是基于OpenPCDet系列的，里面都是绑定了GPU的。
我们暂时不知道任何基于CPU的模型。

At present, they are all based on the OpenPCDet series, and all of them are bound with GPU.
We don't know of any CPU-based models for now.
