### ISSUE TITLE
point-cloud-object-detection diffent

### ISSUE THREAD

**Issue by smallzhao** [xtreme1-io/xtreme1#133]
Hi,
Thanks for your open source work,it's very useful for us
We found that using basicai/xtreme1-point-cloud-object-detection
The detection results for point clouds are worse than those in app.basic.ai. Do these two use the same detection model? Has app.basic.ai been optimized?

**Comment by nicozhan** [comment]
On the Cloud version we use a different model with more data training, so it is better than Xtreme1's model!
Also, we will soon release a tutorial - Integrating [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)!

**Comment by smallzhao** [comment]
> On the Cloud version we use a different model with more data training, so it is better than Xtreme1's model! Also, we will soon release a tutorial - Integrating [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)!
Looking forward to your next work
I uploaded the data to the cloud version, and found that the detection and tracking works very well. You still use Centerpoint for detection, but ABMOT3D for tracking? We are also making similar attempts, but the results are not as good as yours. Can you provide us with some suggestion

**Comment by nicozhan** [comment]
Our tracking principle is consistent with AB3DMOT, but many details are designed by ourselves, such as tracking variables of Kalman filter, distance function, etc. 
In addition, tracking depends on the accuracy of target detection. 
Only when the detection is accurate can the tracking be accurate.

**Comment by smallzhao** [comment]
Thank you for your prompt reply
Are you using Centerpoint for detection? It seems to work very well. Our use of Centerpoint is not as effective as yours, and of course it may also be related to our data volume. Can you ask how much data you used to achieve this effect, and can you share your algorithm configuration. Thanks

**Comment by smallzhao** [comment]
Our configuration file is as follows
`_base_ = [
    '../_base_/datasets/lidar.py',
    '../_base_/models/centerpoint_01voxel_second_secfpn_nus.py',
    '../_base_/schedules/cyclic_20e.py', '../_base_/default_runtime.py'
]
dataset_type = 'LidarDataset'
data_root = '/data2/lidar/LIDAR/'
file_client_args = dict(backend='disk')

class_names = [
    'cone', 'car', 'bicycle', 'motocycle','tricycle','pedestrian',
            'other_vehi', 'bus', 'cyclist', 'truck'
]
workflow = [('train', 1),('val', 1)]
runner = dict(type='EpochBasedRunner', max_epochs=200)
eval_interval=1
voxel_size = [0.075, 0.075, 0.2]
point_cloud_range = [-54, -54, -5.0, 54, 54, 3.0]
# For nuScenes we usually do 10-class detection

model = dict(
    pts_voxel_layer=dict(
        voxel_size=voxel_size, point_cloud_range=point_cloud_range),
    pts_middle_encoder=dict(sparse_shape=[41, 1440, 1440]),
    pts_bbox_head=dict(
        bbox_coder=dict(
            voxel_size=voxel_size[:2], pc_range=point_cloud_range[:2]),
        tasks=[
            dict(num_class=1, class_names=['car']),
            dict(num_class=2, class_names=['truck', 'other_vehi']),
            dict(num_class=1, class_names=['bus']),
            dict(num_class=4, class_names=['motocycle', 'bicycle','tricycle','cyclist']),
            dict(num_class=2, class_names=['pedestrian', 'cone']),
        ],
        common_heads=dict(
            reg=(2, 2), height=(1, 2), dim=(3, 2), rot=(2, 2))
            ),
    train_cfg=dict(
        pts=dict(
            grid_size=[1440, 1440, 40],
            voxel_size=voxel_size,
            point_cloud_range=point_cloud_range)),
    test_cfg=dict(
        pts=dict(voxel_size=voxel_size[:2], pc_range=point_cloud_range[:2])))

`

**Comment by nicozhan** [comment]
Add me on WeChat
