### ISSUE TITLE
run  docker compose up, then reported the error in the picture。Excuse me How to solve

### ISSUE THREAD

**Issue by Hjyperfect** [xtreme1-io/xtreme1#134]
![image](https://github.com/xtreme1-io/xtreme1/assets/50474270/00473c8e-9a2b-4d8b-9b34-fa3b739e5e29)

**Comment by Hjyperfect** [comment]
I used the local startup project

**Comment by Hjyperfect** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/50474270/273330a9-b9d2-40eb-a6d3-deffec85dbe2)
run  docker compose build  then reported the error in the picture

**Comment by Hjyperfect** [comment]
If you do not use docker to start each front-end project and then start the back-end project using yarn serve, you can also start the project, but the interface reports errors and expired errors. Can you give the local direct debugging tutorial

**Comment by Hjyperfect** [comment]
Can you quickly give the solution, I now encountered the same functional development needs reference, thank you very much, sincerely

**Comment by chua1989** [comment]
@Hjyperfect  This link has the solution you want.  https://stackoverflow.com/questions/67399785/how-to-solve-npm-install-error-npm-err-code-1

**Comment by chua1989** [comment]
@Hjyperfect If there are no other issues, I will close this issue
