### ISSUE TITLE
3D Polygon and Polyline annotation

### ISSUE THREAD

**Issue by sarathsrk** [xtreme1-io/xtreme1#135]
I have noticed that the beta (online version) of this tool has an option to create 3D polygon/polyline annotation and segmentation as well. But we don't have that option in the current version (0.7.1) of this tool. Is there any possibility to install the beta version using the Docker method?

**Comment by nicozhan** [comment]
Hi @sarathsrk 
These features are only available on the Cloud version. 

Please contact me for the cloud and on-premises packages.
nico@basic.ai

**Comment by sarathsrk** [comment]
Ok sure. Thanks
