### ISSUE TITLE
How should i upload images to the 2D & 3D LiDAR Fusion ? 

### ISSUE THREAD

**Issue by Acuno41** [xtreme1-io/xtreme1#136]
Hello everyone,

Thanks for the great work.
I have a question about uploading images to the annotation tool.
Should i upload raw images or intrinsic distortion corrected images to the annotation tool ?

**Comment by nicozhan** [comment]
Hi @Acuno41 !
I have seen both.  Do your algorithms or application are based on **intrinsic distortion corrected images**?

**Comment by Acuno41** [comment]
Hi @nicozhan,

Sorry for the late reply.
Yes, i'am gonna feed my system with intrinsic distortion corrected images.
My question is, should i upload intrinsic calibration corrected images to the annotation tool to see the correct projection to the image domain when i annotate object from lidar domain ?

**Comment by nicozhan** [comment]
Hi @Acuno41 !

**Comment by aubeena007** [comment]
@nicozhan  I'm having trouble joining the Slack workspace. It seems like Gmail accounts aren't allowed. Are there any other ways to join?

**Comment by nicozhan** [comment]
> @nicozhan I'm having trouble joining the Slack workspace. It seems like Gmail accounts aren't allowed. Are there any other ways to join?
Try this link:
https://join.slack.com/t/xtreme1io/shared_invite/zt-2l5k6mwro-XrQyZFGyQNfvztyDDTZH3Q
