### ISSUE TITLE
YOLOR&RITM model

### ISSUE THREAD

**Issue by 1572161937** [xtreme1-io/xtreme1#137]
After viewing the codes, I know that xtreme1 is a platform which can used any models, the demo in README.md looks good(
Image Annotation (B-box, Segmentation) - [YOLOR](https://github.com/WongKinYiu/yolor) & [RITM](https://github.com/saic-vul/ritm_interactive_segmentation)), so I want to know if these two model are defaultly build-in? Should I need to "create my model" to use these two models? if so, please give me some guidance, thank you!

**Comment by nicozhan** [comment]
Hi @1572161937 !
Welcome to use Xtreme1!

> so I want to know if these two model are defaultly build-in? 

Pre-annotation model YOLOR is available. And you need to setup this model: https://github.com/xtreme1-io/xtreme1#%EF%B8%8F-install-built-in-models Also, you can add your custom model. 
Interactive model RITM is not available on open source version.

I have a 3D detection model intergration with [MMDetection3D](https://github.com/open-mmlab/mmdetection3d). Now we need testing and verification. If you are interested, you can add me

**Comment by 1572161937** [comment]
这是来自QQ邮箱的自动回复邮件：您好，您的邮件我已收到，会尽快给您回复。

**Comment by 1572161937** [comment]
Hi @nicozhan

Thank you for your reply! I would like to confirm once again whether the built-in models installed through `docker compose --profile model up` is YOLOR?
