### ISSUE TITLE
v0.6.1运行图片模型之后 图片上的框没有标签

### ISSUE THREAD

**Issue by wanghaowish** [xtreme1-io/xtreme1#138]
**Describe the bug**
v0.6.1运行图片模型之后 图片上的框没有标签

**To Reproduce**
1. 选中图片数据集选中一张图去标注
2. smart  tool运行图片模型 然后添加结果
3. 图片上出现预标注的框 但是框是没有标签的

**Expected behavior**
图片是的框带有标签信息，这个在点云模型是正常的，但是图片模型有这个问题

**Screenshots**
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/646bef7b-7e20-402e-af83-6dab8dddfd33)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/d51608a1-f1f0-468a-bb6e-3f53dc88cab9)

**Desktop (please complete the following information):**
 - OS: 服务器部署在ubuntu20.04，docker compose 部署的
 - Browser chrome
 - Version v0.6.1

**Comment by 1572161937** [comment]
用英文问试试

**Comment by fanyinbo** [comment]
我们会在后续版本中解决这个问题，不更新版本解决这个问题需要在数据库中执行如下SQL：
DELETE FROM model_class WHERE model_id=2;
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Person', 'person', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bicycle', 'bicycle', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Car', 'car', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Motorcycle', 'motorcycle', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Airplane', 'airplane', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Train', 'train', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Truck', 'truck', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Boat', 'boat', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Traffic Light', 'traffic light', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Fire Hydrant', 'fire hydrant', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Stop Sign', 'stop sign', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Parking Meter', 'parking meter', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bench', 'bench', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bird', 'bird', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Cat', 'cat', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Dog', 'dog', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Horse', 'horse', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Sheep', 'sheep', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Cow', 'cow', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Elephant', 'elephant', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bear', 'bear', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Zebra', 'zebra', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Giraffe', 'giraffe', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Backpack', 'backpack', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Umbrella', 'umbrella', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Handbag', 'handbag', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Tie', 'tie', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Suitcase', 'suitcase', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Frisbee', 'frisbee', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Skis', 'skis', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Snowboard', 'snowboard', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Sports Ball', 'sports ball', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Kite', 'kite', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Baseball Bat', 'baseball bat', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, x`updated_by`) VALUES (2, 'Baseball Glove', 'baseball glove', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Skateboard', 'skateboard', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Surfboard', 'surfboard', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Tennis Racket', 'tennis racket', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bottle', 'bottle', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Wine Glass', 'wine glass', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Cup', 'cup', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Fork', 'fork', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Knife', 'knife', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Spoon', 'spoon', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bowl', 'bowl', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Banana', 'banana', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Apple', 'apple', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Sandwich', 'sandwich', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Orange', 'orange', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Broccoli', 'broccoli', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Carrot', 'carrot', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Hot Dog', 'hot dog', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Pizza', 'pizza', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Donut', 'donut', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Cake', 'cake', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Chair', 'chair', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Couch', 'couch', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Potted Plant', 'potted plant', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bed', 'bed', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Dining Table', 'dining table', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Toilet', 'toilet', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Tv', 'tv', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Laptop', 'laptop', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Mouse', 'mouse', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Remote', 'remote', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Keyboard', 'keyboard', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Cell Phone', 'cell phone', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Microwave', 'microwave', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Oven', 'oven', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Toaster', 'toaster', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Sink', 'sink', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Refrigerator', 'refrigerator', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Book', 'book', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Clock', 'clock', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Vase', 'vase', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Scissors', 'scissors', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Teddy Bear', 'teddy bear', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Hair Drier', 'hair drier', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Toothbrush', 'toothbrush', current_timestamp, 1, NULL, NULL);
INSERT INTO `x1_community`.`model_class`(`model_id`, `name`, `code`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'Bus', 'bus', current_timestamp, 1, NULL, NULL);
