### ISSUE TITLE
Error response from daemon: unknown or invalid runtime name: nvidia

### ISSUE THREAD

**Issue by 1572161937** [xtreme1-io/xtreme1#139]
After ran `docker compose --profile model up`, I met follow error.
![sunlogin_20230815171536](https://github.com/xtreme1-io/xtreme1/assets/102746679/71abc1cf-4cad-444e-9e7f-648d6544d9bc)
I have set the `/etc/docker/daemon.json`.
`nvidia-smi` could show my GPUs successfully.
My environment : win11 22621.675 + docker desktop + WSL2.0 Ubuntu-20.04

**Comment by nicozhan** [comment]
Hi @1572161937 !
After successfully installing `nvidia runtime`, please try to **restart Docker**.

**Comment by 1572161937** [comment]
I have restarted win11, restarted docker, restarted WSL2.0, it doesn't work.
But I am not sure whether I have installed `nvidia runtime`, how can i check it?

**Comment by nicozhan** [comment]
<img width="544" alt="5f36c1bdfa452aada92e6ce412a8f6cd" src="https://github.com/xtreme1-io/xtreme1/assets/84139543/22f39a4c-2ac1-4db8-9b0d-b7d7fb700c81">

If the runtime in docker info contains `nvidia`, the installation is successful. (Refer to nvidia official website for installation.)

**Comment by 1572161937** [comment]
The issue seems to be: 
The Linux server uses the `nvidia-docker` to start CUDA's Docker. While in WSL2.0, the `docker run -- gpus` is used.
However, in the docker-hub package, this module is packaged as a whole and cannot modify the compilation commands.

**Comment by nicozhan** [comment]
We think it's because of WSL 2.0 issue. Please try to use the **Linux system** to install directly.
The compilation parameters in the docker image are all based on the Linux and some of them may not be supported by WSL 2.0.

**Comment by nicozhan** [comment]
Hi @1572161937 Please see https://github.com/xtreme1-io/xtreme1/issues/144
