### ISSUE TITLE
Can we deploy our own pre-label model?

### ISSUE THREAD

**Issue by rOtking** [xtreme1-io/xtreme1#142]
As title

**Comment by nicozhan** [comment]
Yes,

**Comment by Siyeong-Lee** [comment]
Can you provide a detailed explanation of Lidar-camera Fusion Annotation for pre-labeled datasets?  

For me, "dataId" and "classId" can be challenging to fill in with information. Specifically, it is difficult to determine the purpose of the "classValues" field. Additionally, I'm curious if there are any specific rules or requirements for the id/track id information.

**Comment by nicozhan** [comment]
Hi [Siyeong-Lee](https://github.com/Siyeong-Lee)!

Indeed, some values are not required.
Please join our [Slack channel](https://join.slack.com/t/xtreme1io/shared_invite/zt-1jhk36uzr-NpdpYXeQAEHN6rYJy5_6pg) and our support team can help you with the json format.
