### ISSUE TITLE
Inquiries about the feature "group a scene" support

### ISSUE THREAD

**Issue by Siyeong-Lee** [xtreme1-io/xtreme1#143]
Thank you for sharing the source code of the annotation tool. 

I was wondering if there are any plans to add a feature that groups data included in the [[Xtreme1 online version](https://app.basic.ai/#/login/)](https://app.basic.ai/#/login/). This feature would be helpful for more users to utilize Xtreme.

**Comment by nicozhan** [comment]
Hi [Siyeong-Lee](https://github.com/Siyeong-Lee)!
**Scene** feature currently is only available on BasicAI cloud version.
For open source Xtreme1 project, the next update will be 3D segmentation feature.

**Comment by Siyeong-Lee** [comment]
@nicozhan Thank you!
