### ISSUE TITLE
some ideas about 'Enable model services' section

### ISSUE THREAD

**Issue by 1572161937** [xtreme1-io/xtreme1#144]
> ## Enable model services

> > Make sure you have installed [NVIDIA Driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html) and [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker). But you do not need to install the CUDA Toolkit, as it already contained in the model image.

> ```bash
> # You need set "default-runtime" as "nvidia" in  /etc/docker/daemon.json and restart docker to enable NVIDIA Container > Toolkit
> {
>  "runtimes": {
>    "nvidia": {
>      "path": "nvidia-container-runtime",
>      "runtimeArgs": []
>    }
>  },
>  "default-runtime": "nvidia"
> }
In `Enable model services` section, you need set `default-runtime` as `nvidia`. If you use `Docker Desktop` + `WSL2.0`, you have to set it at `Docker Engine` of `Docker Desktop` just like the picture below.

![企业微信截图_16929318134631](https://github.com/xtreme1-io/xtreme1/assets/102746679/aeb0f077-6426-494f-892c-8095505854d6)

**Comment by nicozhan** [comment]
May I ask if you have successfully run the platform through `WSL 2.0`?
Is it because some components do not support `WSL2.0`, causing the platform to fail?

**Comment by 1572161937** [comment]
Yes, I have successfully run the platform through `Docker Desktop` + `WSL2.0`.

**Comment by nicozhan** [comment]
Great! I will update it to Readme!

**Comment by Fabio-Arup-Panella** [comment]
I am trying to annotate images for semantic segmentation. I would like to make use of pretrained models to assist this segmentation.
However, COCO for Object detection is the only available model.

Info:
Processor: 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz   2.61 GHz
Installed RAM: 64.0 GB
OS: Windows 10 Enterprise
WSL2 Description:
     Ubuntu 22.04.4 LTS
     Release:        22.04
     Codename:       jammy
     
![image](https://github.com/xtreme1-io/xtreme1/assets/69897365/e12790bd-b35d-437a-b576-bc23c42d64e7)

**Comment by Yukun-Cui** [comment]
这是来自QQ邮箱的自动回复邮件：您好，您的邮件我已收到，会尽快给您回复。

**Comment by Fabio-Arup-Panella** [comment]
Do you have any pre-trained model for semantic segmentation?
Fabio
________________________________
