### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by Hjyperfect** [xtreme1-io/xtreme1#153]
Which version or branch of code is on the line

**Comment by Hjyperfect** [comment]
The code on the line is the history route，github pull down the code startup hand is hash routing Excuse me how to update to the latest code online

**Comment by nicozhan** [comment]
Hi @Hjyperfect ! 
Q1:
`Xtreme1` is the open source project.
`online (cloud) version` is different from it and it is no open source.

Q2:
To update to the latest version, you need to manually delete the previous version, pull the most recent code, and perform the installation.

Contact me if you need more info
