### ISSUE TITLE
Script to Download original data

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#154]
Hi,
I'm trying to create a script to download original data such as Images or Point Cloud. 

When I try to use requests.request(method='GET', url=data_content["pointCloudUrl"]), I have this error : 
`<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`
How should I call the request to beeing able to download pointcloud and images in a python script ? 

Thanks a lot. 
Clément

**Comment by fanyinbo** [comment]
Please provide the pointCloudUrl address where the error was reported.

**Comment by ClementLeBihan** [comment]
The URL is something like : 
`"pointCloudUrl":"http://minio:9000/x1-community/2/12/64faafd5cfb44093bff7fe353b19a230/XXX.2023-09-26.09-26-50.3/point_cloud/000000.pcd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20231023%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231023T132908Z&X-Amz-Expires=6048X00&X-Amz-SignedHeaders=host&X-Amz-Signature=4c656e8676a48ddezdzedez539b2dad814e33cbce30a4d8b`

Removing all the params after 000000.pcd make it downloadable :)
