### ISSUE TITLE
Support fisheye camera type 

### ISSUE THREAD

**Issue by Siyeong-Lee** [xtreme1-io/xtreme1#155]
Are you planning to support the fisheye camera type?

**Comment by samyak86** [comment]
Yes

**Comment by nicozhan** [comment]
Currently, the platform cannot directly support it.
Fisheye images can be imported into the platform after being de-distorted.

**Comment by nicozhan** [comment]
Cloud version (https://app.basic.ai/#/login) support to upload fisheye camera.
