### ISSUE TITLE
uploaded images and point cloud not coinciding because exact camera parameter config files needed, how to create them with available inputs?

### ISSUE THREAD

**Issue by Ragavi1209** [xtreme1-io/xtreme1#156]
I  have to upload lidar fusion in Xtreme1, I can upload them but point cloud data and image not coinciding, when annotate box not placing in 2D images which I uploaded, because of issue with my config files, what should I do?

Available camera parameter values :

      "rgb_highres_center": {
        "type": "camera",
        "uri": "rgb_highres_center",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              7267.95450880415,
              0,
              2056.049238502414,
              0,
              0,
              7267.95450880415,
              1232.862908875167,
              0,
              0,
              0,
              1,
              0
            ],
            "distortion_coeffs": [
              -0.0764891,
              -0.188057,
              0,
              0,
              1.78279
            ],
            "width_px": 4112,
            "height_px": 2504
          }
        }
      }

config file I have tried (derived from available parameter values by me):

[
    {
    "camera_internal": {
        "fx": 7267.95450880415,
        "fy": 7267.95450880415,
        "cx": 2056.049238502414,
        "cy": 1232.862908875167
    },
    "width": 4112,
    "height": 2504,
    "camera_external": [
        -0.0764891,
        -0.188057,
        0,
        0,
        1.78279,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
    ],
    "rowMajor": false

not coincides with point cloud data:
![image](https://github.com/xtreme1-io/xtreme1/assets/146808472/af8c283d-51ae-49f2-9dff-3720f2293760)

I need data be like:

![image](https://github.com/xtreme1-io/xtreme1/assets/146808472/1d03dc89-1780-4f94-b0e9-ac7e4b996576)

Anyone kindly give me a solution asap............

**Comment by nicozhan** [comment]
You mistakenly filled in the distortion parameters as external parameters.
The original data lacks **extrinsic** parameters, can you provide them?

**Comment by Ragavi1209** [comment]
I have the below parameters only...

"rgb_highres_center": {
    "type": "camera",
    "uri": "rgb_highres_center",
    "stream_properties": {
      "intrinsics_pinhole": {
        "camera_matrix": [
          7267.95450880415,
          0,
          2056.049238502414,
          0,
          0,
          7267.95450880415,
          1232.862908875167,
          0,
          0,
          0,
          1,
          0
        ],
        "distortion_coeffs": [
          -0.0764891,
          -0.188057,
          0,
          0,
          1.78279
        ],
        "width_px": 4112,
        "height_px": 2504
      }
    }
  }

**Comment by Siyeong-Lee** [comment]
Do you also support camera distortion parameters?

**Comment by Ragavi1209** [comment]
yes , which is mentioned below

"distortion_coeffs": [
-0.0764891,
-0.188057,
0,
0,
1.78279

and additionally

"rgb_highres_center": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [
            0.0801578,
            -0.332862,
            3.50982
          ],
          "quaternion": [
            -0.00313306,
            0.0562995,
            0.00482918,
            0.998397
          ]
        }
      }

these values too
