### ISSUE TITLE
Polyline disappearing after finish drawing

### ISSUE THREAD

**Issue by Ragavi1209** [xtreme1-io/xtreme1#159]
The bug is about polyline in Xtreme1 open source cloud version tool,
When I draw a line on image, line disappearing after finish my drawing **(refer attached video).**

Once I saved my annotation and refreshed a link only line appearing, so it is found as a bug. kindly fix it and let me know update asap.

https://github.com/xtreme1-io/xtreme1/assets/146808472/345c5e2d-0557-48d8-b93b-8bd92e3c5085

**Comment by jaggerwang** [comment]
Fixed on main and dev branch, but the release package needs some time.

**Comment by Ragavi1209** [comment]
> Fixed on main and dev branch, but the release package needs some time.

okay sure let me check, once it released let me know
