### ISSUE TITLE
Differences between XTreme1/community and Cloud version 

### ISSUE THREAD

**Issue by jlvila** [xtreme1-io/xtreme1#164]
All,

I'm just starting using the platform (Community 0.7.2 and cloud version).
For sure, there are differences between Community version and Cloud one. But:
- I can't see the semantic segmentation (tool) into community version as pre-built model, is there a way to activate/activate them (LiDAR and Image) ;
- Is there a more accurate documentation to integrate new models?
- Is there a comparison matrix for both version?
Thanks for your answers,
Jean-Louis

**Comment by nicozhan** [comment]
Thanks for your quesiton:

Q1 and Q3:

|Main features |  Xtreme1 v0.7.2 | BasicAI Cloud v0.12.2|
|:-------------------------:|:-------------------------:|:-------------------------:|
| Lidar Basic | ✅|✅|
| 2D/3D Lidar-camera fusion| ✅|✅|
| 3D Segmetation| ⛔ |✅|
| 3D Tracking | ⛔|✅|
| 3D Lane/line| ⛔|✅|
| Image | ✅|✅|
| Image Brush | ⛔|✅|
| Image/video Tracking | ⛔|✅|
| Audio/video | ⛔|✅|
| Text| ✅RLHF Annotation tool (beta)|Coming soon|
|Task Management|⛔|✅|
|Ontology|✅Advanced features|✅|

Q2: Is there a more accurate documentation to integrate new models?
We have a tutorial that we haven't published yet that might help you.

**Comment by e1eustac** [comment]
Hi,
I can't find Lidar Basic feature in BasicAI Cloud. Could you explain how to use it, pls.
I want to annotate Lidar and front camera data and export in kitti format, but with 'Lidar Fusion" feature, only projected object are exported.
Thank you for your help,
Regards
Yvan

**Comment by jotamotk** [comment]
Hi, Yvan @e1eustac 
Please discuss [here]( https://github.com/xtreme1-io/xtreme1/issues/208 )
