### ISSUE TITLE
Failed to build frontend when building from source code

### ISSUE THREAD

**Issue by LishaTang** [xtreme1-io/xtreme1#171]
Docker installation was successful, but errors occurred while compiling the source code and running "docker compose build" to build the container, specifically during the compilation of frontend/main. I've checked the issues but haven't found a solution. Could you help me identify what the problem might be?
environment:  win10, docker-desktop
<img width="876" alt="xtreme1xxxxxxxxxx" src="https://github.com/xtreme1-io/xtreme1/assets/48672236/6ae1a2f3-5a15-4471-b61f-58480403a222">

**Comment by chua1989** [comment]
@LishaTang The reason is that you cannot access npm's official registry.npmjs.org. You can use domestic mirrors, such as cnpm, npmmirror, etc.

**Comment by DiZ-gogogo** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/114937721/eb9a87d1-c3db-4e1a-90d1-9909878751c3)
I encountered a similar issue, but when I replaced npm with cnpm, a new bug emerged. How can I resolve this? thank you.

**Comment by chua1989** [comment]
@DiZ-gogogo may be useful to you https://gist.github.com/deepak-cotocus/0238d919153cb7dce1cd0bdda41e2973

**Comment by DiZ-gogogo** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/114937721/2836820e-5c7f-46cb-ab6b-60713cbd7b42)
I want to run the 'pc-tool' component independently. How can I retrieve and display the data? Thanks!

**Comment by jaggerwang** [comment]
Sorry, the pc tool cannot be running independently from the main app right row.

**Comment by guhaomine** [comment]
@DiZ-gogogo All backend requests are under the pc-tool/src/api directory, you need to rewrite these logics.
