### ISSUE TITLE
how to hot reloading using vue+nginx in docker

### ISSUE THREAD

**Issue by Alexanderisgod** [xtreme1-io/xtreme1#172]
i want to modify the frontend, but i'm new to the frontend develop, could tell me how to modify the dockerfile to realize hot reloading?
`
# syntax=docker/dockerfile:1
FROM node:16 as build
WORKDIR /build
COPY . .
RUN --mount=type=cache,target=main/node_modules \
    cd main && npm install && npm run build
RUN --mount=type=cache,target=image-tool/node_modules \
    cd image-tool && npm install && npm run build
RUN --mount=type=cache,target=pc-tool/node_modules \
    cd pc-tool && npm install && npm run build
RUN --mount=type=cache,target=text-tool/node_modules \
    cd text-tool && npm install && npm run build

FROM nginx:1.22
COPY --from=build /build/dist /usr/share/nginx/html
`

**Comment by jaggerwang** [comment]
<img width="1580" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/1255011/1b4114f3-d82d-49bd-b0d6-9964e77c7e21">
You do not need to hot reload Docker! After you started all docker compose services, you can configure your local frontend development to proxy api request to nginx service, and vite already support hot reloading.

**Comment by Alexanderisgod** [comment]
> <img alt="image" width="1580" src="https://private-user-images.githubusercontent.com/1255011/288658246-1b4114f3-d82d-49bd-b0d6-9964e77c7e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzQ3MTQsIm5iZiI6MTcwMTkzNDQxNCwicGF0aCI6Ii8xMjU1MDExLzI4ODY1ODI0Ni0xYjQxMTRmMy1kODJkLTQ5YmQtYjBkNi05OTY0ZTc3YzdlMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDczMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUyNTlkMDhlNzAxOTMzYzk0MWM3YjY2Y2Q0ZmJlY2Q3OTg2ZGE1ZTM0ZjU4ZGQ5MTY2M2Y3MjdlNjQ3N2ViOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gDsxa20ArH6CQuTLYFCRa8lMmAVhWp3ZJOdVqqFc3qg"> You do not need to hot reload Docker! After you started all docker compose services, you can configure your local frontend development to proxy api request to nginx service, and vite already support hot reloading.

i want to add some functions on the frontend in develop mode, but i change some element the webpage didn't change.
so what's the meaning of 'local frontend development'? 
![2023-12-07 15-40-44 的屏幕截图](https://github.com/xtreme1-io/xtreme1/assets/41862202/6142831a-9716-4cdd-b5b4-6327d37f3656)

**Comment by Alexanderisgod** [comment]
> <img alt="image" width="1580" src="https://private-user-images.githubusercontent.com/1255011/288658246-1b4114f3-d82d-49bd-b0d6-9964e77c7e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzQ3MTQsIm5iZiI6MTcwMTkzNDQxNCwicGF0aCI6Ii8xMjU1MDExLzI4ODY1ODI0Ni0xYjQxMTRmMy1kODJkLTQ5YmQtYjBkNi05OTY0ZTc3YzdlMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDczMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUyNTlkMDhlNzAxOTMzYzk0MWM3YjY2Y2Q0ZmJlY2Q3OTg2ZGE1ZTM0ZjU4ZGQ5MTY2M2Y3MjdlNjQ3N2ViOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gDsxa20ArH6CQuTLYFCRa8lMmAVhWp3ZJOdVqqFc3qg"> You do not need to hot reload Docker! After you started all docker compose services, you can configure your local frontend development to proxy api request to nginx service, and vite already support hot reloading.

i just want do some change in the docker environment, so it's feasible？

**Comment by jaggerwang** [comment]
Dockerfile does not support hot reloading, you need to rebuild the frontend image and restart docker compose services, please refer [Build Xtreme1 from source code](https://docs.xtreme1.io/xtreme1-docs/get-started/install-from-source).

**Comment by Alexanderisgod** [comment]
> Dockerfile does not support hot reloading, you need to rebuild the frontend image and restart docker compose services, please refer [Build Xtreme1 from source code](https://docs.xtreme1.io/xtreme1-docs/get-started/install-from-source).

 Thank for you reply. i build it form souce code, i found that i have to rebuild it  if i change some code to make it work. I want it hot reloading in docker env, so it's infeasible?
![2023-12-07 15-59-09 的屏幕截图](https://github.com/xtreme1-io/xtreme1/assets/41862202/a73e5573-87b8-4b7a-b8fa-962e370324eb)
