### ISSUE TITLE
makeFrameSeriesApi calls deleted api calls

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#174]
Hi,
I would love to use the makeFrameSeriesApi function to group successive frames into a scene in my dataset. 
Unfortunately, it looks like this part of backend hasn't been published. 

Is it possible to publish it ? 
If not, may you help to write it ? 

I saw @guhaomine created a branch feat:scene but no modification has been done in main frontend (to group/ungroup frames) and backend.

Best,
Clément

**Comment by jaggerwang** [comment]
V0.8 will be released at the end of this month, supporting point cloud frame annotation. At that time, frame can be uploaded through zip package (not supported creating in app), and then label it in the tool.

**Comment by ClementLeBihan** [comment]
Nice to have point cloud frame annotation ! But I would like to have the possibility to do it in app. I don't understand where the frame/combine api backend is ? Did you delete it on purpose ? 
I understand you do not have enough manpower to guide everyone how to develop, but in this case I imagine the code already exist somewhere as the makeFrameSeriesApi function existed in the first commit. So I guess the backend function existed also, right ?

**Comment by jaggerwang** [comment]
The frame related apis does not exist in the backend, it belongs to the cloud edition only right now. We have received your suggestion and will evaluate whether it is possible to open source this part of the functionality in the future.
