### ISSUE TITLE
Access denied for user 'xtreme1'

### ISSUE THREAD

**Issue by Siyeong-Lee** [xtreme1-io/xtreme1#179]
**Describe the bug**
After the v0.8 version update, the mysql container is not creating after entering the command `docker compose up `.
Please let me know what I can try.

**To Reproduce**
```
docker compose up
```
error logs:
xtreme1-mysql-1                     | 2024-01-02T09:34:52.980564Z 2 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu20.04

**Additional context**

**Comment by jaggerwang** [comment]
V0.8 is not compatible with previous version, you should run `docker compose down -v` to clear the old data. Be careful, you will lose all your data! For more information, you can reference https://docs.xtreme1.io/xtreme1-docs/get-started/install-with-docker.

**Comment by Siyeong-Lee** [comment]
Thanks!
