### ISSUE TITLE
Changing max_allowed_packet

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#182]
Hi,

Yesterday I did 3 hours of annotations, but when I saved, I got this error message (and lost all my annotation :cry:) :
`### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (6,032,035 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.`
Where can I change this max_allowed_packet variable ?

**Comment by jaggerwang** [comment]
Xtreme1 is using the official DockerHub MySQL image, you can reference the official docs to customize it's configuration, https://hub.docker.com/_/mysql. Thanks for your feedback, we will consider to increase the default `max_allowed_packet` of MySQL in the Docker Compose file.

![image](https://github.com/xtreme1-io/xtreme1/assets/1255011/7958db90-c696-4caf-bfa8-d45df13611f3)

**Comment by jaggerwang** [comment]
It already been hotfixed on main branch, you can reference the commit 9d5b8a17cc227c44815eff5b6e5272b9913b535a.

**Comment by ClementLeBihan** [comment]
Wow awesome ! Thanks !
