### ISSUE TITLE
how to classification

### ISSUE THREAD

**Issue by hey221comeon** [xtreme1-io/xtreme1#184]
can not find add class button , only can find car, truck and van.
Please tell me how to add customized categories, like ground or sign.
![image](https://github.com/xtreme1-io/xtreme1/assets/127086089/99fcc5fd-12f0-4d5a-9b59-e4dae467b308)

**Comment by jotamotk** [comment]
You need to go to the ontology tab of your dataset, and set ground or sign. as a class, or set Weather as a classification
