### ISSUE TITLE
Lidar Segmentation and Projection

### ISSUE THREAD

**Issue by haamoon** [xtreme1-io/xtreme1#186]
Hi, thank you for the excellent work! Xtreme is the most powerful open-source LiDAR annotation tool available online. I am curious if there is any ongoing effort to support per-point LiDAR annotation through a brush tool and/or 3D polygon. The closet thing I could find is [hitachi annotator](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor) but it lacks certain features such as 2D projection.

Additionally, it would be highly beneficial if the segmentation masks could be projected onto the image views, similar to the 3D bounding boxes. I am willing to contribute to the development of these features if they align with Xtreme's development roadmap.

**Comment by haamoon** [comment]
I just realized that the cloud version supports 3D segmentation! I am wondering if you have any plans to release the source code for segmentation or not?

**Comment by jotamotk** [comment]
Yes, we are planning to open-source 90% of our tool sets in our SaaS. The PC segmentation features will likely be available around May of this year. Balancing our resources between the SaaS and Open-source version is a significant challenge, and we greatly appreciate your contribution to our code. Let's stay in touch!

In the meantime, we offer a long-term free SaaS plan for small teams with fewer than 5 members. Feel free to use our [SaaS ](https://www.basic.ai/)with full features

**Comment by haamoon** [comment]
I appreciate the update on your plans to open-source the majority of your tool sets. I look forward to the PC segmentation features in May, and I'm glad to contribute to your code if needed. Let's definitely stay in touch, and please keep up the excellent work!

**Comment by jaggerwang** [comment]
Yes, you can fork our repository to add the features you needed if you urgently need it.

**Comment by jotamotk** [comment]
Yes, we will open-source image segmentation after point cloud segmentation. It wouldn't be soon.

**Comment by jacoblambert** [comment]
Just wanted to second that the Point Cloud 3D Segmentation tool would be a great addition to the open-source tool since it's a rare feature, in particular not available in CVAT. Thanks for your great work.

**Comment by ClementLeBihan** [comment]
Hi @jaggerwang,
Any update on the release of semantic segmentation feature ? You said in this ticket around May 2024, do you have any update on the subject ?

**Comment by jaggerwang** [comment]
Unfortunately, due to manpower problems, we have temporarily shelved this plan.

**Comment by ClementLeBihan** [comment]
Hi @jaggerwan.
Do you have any update regarding the @jotamotk quote "we are planning to open-source 90% of our tool sets in our SaaS" ?
