### ISSUE TITLE
使用url上传带预标注结果的数据 无法正常显示预标注结果（When using urls to upload data with premarked results, the premarked results cannot be displayed properly）

### ISSUE THREAD

**Issue by wanghaowish** [xtreme1-io/xtreme1#188]
我使用zip文件方式上传 可以正常上传 并且显示出预标注结果，但是同一个zip文件 我使用url方式上传时却不能显示预标注结果了
When I upload a zip file, I can upload it normally and display the pre-annotated results. However, when I upload the same zip file using the url, I cannot display the pre-annotated results
zip方式上传
zip upload
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/2190d91b-241a-4821-bf8c-43ebd7ff643e)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/e95a114f-ceec-4619-aabb-0f0f0cf5fc6c)
url方式上传
url upload
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/734c38a0-8ad7-4fde-bc7f-faa34f8713c6)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/feb63f0a-453f-45ec-aeca-9026745bc663)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/4f2433f3-0bc7-4909-b770-87b38febe610)
我是用的Xtreme版本是v0.6.1
I am using Xtreme version v0.6.1

**Comment by jaggerwang** [comment]
Please try the latest v0.8.1.

**Comment by wanghaowish** [comment]
我重新部署了一套v0.8.1 依然存在这个问题
I redeployed it of v0.8.1 and still had this problem
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/a4f27c57-30d1-4d86-b88d-623977d478a8)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/a89c6c1f-958f-4237-89ca-a9b6fb0d635c)
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/4540c334-6e3f-4577-ac3d-96d1220b851d)

而且我还发现v0.8.1的一个bug,由于他上传的文件结构从image改成了image_0，所以我修改了我的zip里面的image文件夹的名称，然后我上传之后发现 我的图片的名称不是正确的了。
Moreover, I also found a bug in v0.8.1, because the file structure he uploaded was changed from image to image_0, so I changed the name of the image folder in my zip, and then I found that the name of my image was not correct after uploading.
this is v0.8.1
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/1d0c2754-17c7-4875-a08e-bf7560192bcb)
这个是v0.6.1版本
this is v0.6.1
![image](https://github.com/xtreme1-io/xtreme1/assets/34294012/236da87c-010c-4811-a44c-54298eca767d)

**Comment by chua1989** [comment]
@wanghaowish v0.8.1已经修复该问题
