### ISSUE TITLE
Use Three-Fatline to enable linewidth in firefow

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#194]
Hi,

In Xtreme1, Box Linewidth doesn't work on firefox : 
Due to limitations of the [OpenGL Core Profile](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf) with the [WebGL](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer) renderer on most platforms linewidth will always be 1 regardless of the set value.

Can we use three-fatline (exemple : https://threejs.org/examples/webgl_lines_fat.html) instead to make it work in firefox ? 

Best,
Clément

**Comment by guhaomine** [comment]
Hi, we currently do not support the function of changing line width, and there are currently no plans to use three-fatline.
