### ISSUE TITLE
Can not support gpu of 4090?

### ISSUE THREAD

**Issue by yvanwy** [xtreme1-io/xtreme1#196]
point-cloud-object-detection-1  | 2024-02-04 15:32:30 INFO log_interval: LOAD pcd:                 0.0015s
point-cloud-object-detection-1  | 2024-02-04 15:32:30 INFO log_interval: VALIDATE points:          0.016s
point-cloud-object-detection-1  | 2024-02-04 15:32:31 ERROR process_data: CUDA error: no kernel image is available for execution on the device
point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
point-cloud-object-detection-1  | Traceback (most recent call last):
point-cloud-object-detection-1  |   File "app.py", line 80, in process_data
point-cloud-object-detection-1  |     results, _ = self.predictor(points=pc, full_nms=True)
point-cloud-object-detection-1  |   File "/app/pcdet_open/src/predictor.py", line 80, in __call__
point-cloud-object-detection-1  |     pred_dicts, _ = self.model.forward(data_dict)
point-cloud-object-detection-1  |   File "/src/pcdet/models/detectors/centerpoint.py", line 11, in forward
point-cloud-object-detection-1  |     batch_dict = cur_module(batch_dict)
point-cloud-object-detection-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
point-cloud-object-detection-1  |     return forward_call(*input, **kwargs)
point-cloud-object-detection-1  |   File "/src/pcdet/models/backbones_3d/vfe/mean_vfe.py", line 26, in forward
point-cloud-object-detection-1  |     points_mean = voxel_features[:, :, :].sum(dim=1, keepdim=False)
point-cloud-object-detection-1  | RuntimeError: CUDA error: no kernel image is available for execution on the device
point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by wuyudian1** [comment]
The version of CUDA used by our "Point Cloud Object Detection Model" is 10.2, which does not support the RTX3080 or later ones。 However, you can build your own image from our source code using a newer version of CUDA and PyTorch.  For guidance, you can refer to this [similar issue](https://github.com/xtreme1-io/xtreme1/issues/170)

**Comment by Creating-ZXY** [comment]
> point-cloud-object-detection-1  | 2024-02-04 15:32:30 INFO log_interval: LOAD pcd:                 0.0015s
> point-cloud-object-detection-1  | 2024-02-04 15:32:30 INFO log_interval: VALIDATE points:          0.016s
> point-cloud-object-detection-1  | 2024-02-04 15:32:31 ERROR process_data: CUDA error: no kernel image is available for execution on the device
> point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> point-cloud-object-detection-1  | Traceback (most recent call last):
> point-cloud-object-detection-1  |   File "app.py", line 80, in process_data
> point-cloud-object-detection-1  |     results, _ = self.predictor(points=pc, full_nms=True)
> point-cloud-object-detection-1  |   File "/app/pcdet_open/src/predictor.py", line 80, in __call__
> point-cloud-object-detection-1  |     pred_dicts, _ = self.model.forward(data_dict)
> point-cloud-object-detection-1  |   File "/src/pcdet/models/detectors/centerpoint.py", line 11, in forward
> point-cloud-object-detection-1  |     batch_dict = cur_module(batch_dict)
> point-cloud-object-detection-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
> point-cloud-object-detection-1  |     return forward_call(*input, **kwargs)
> point-cloud-object-detection-1  |   File "/src/pcdet/models/backbones_3d/vfe/mean_vfe.py", line 26, in forward
> point-cloud-object-detection-1  |     points_mean = voxel_features[:, :, :].sum(dim=1, keepdim=False)
> point-cloud-object-detection-1  | RuntimeError: CUDA error: no kernel image is available for execution on the device
> point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Have you resolved this issue? Could you please share the detailed solution?
