### ISSUE TITLE
Kitti formats only export projected objects

### ISSUE THREAD

**Issue by jotamotk** [xtreme1-io/xtreme1#208]
Hi,
I can't find Lidar Basic feature in BasicAI Cloud. Could you explain how to use it, pls.
I want to annotate Lidar and front camera data and export in kitti format, but with 'Lidar Fusion" feature, only projected object are exported.
Thank you for your help,
Regards
Yvan

_Originally posted by @e1eustac in https://github.com/xtreme1-io/xtreme1/issues/164#issuecomment-1968410760_

**Comment by jotamotk** [comment]
Hi Yvan,
We have merged LiDAR Basic datatype into LiDAR Fusion into our cloud version and have yet to migrate to Xtreme1.

If you have previous LIDAR Basic zip files, you can directly upload them to a LiDAR fusion dataset. See sample datasets [here](https://basicai-asset.s3.amazonaws.com/docs/LiDAR%20Dataset/LiDAR_Fusion_without_images.zip)

We currently only support converting 3D results with the 2D results for Kitti formats. However, we can add a script for you; please provide the following information:
1. Which version are you trying to export, cloud or Xtreme1?
2. Please provide your expected Kitti-like format details

Regards,
James

**Comment by e1eustac** [comment]
Hi James,
Thank you for your answer. I will soon test the fusion basic feature in cloud platform.
1. I have tried to export with cloud and Xtreme1.  With cloud platform, only projected objects are exported. With Xtreme1 and export script (xtreme1.script_ctl form xtrem1-sdk v0.6), kitti directory is empty.
Example:
python -m xtreme1.script_ctl --mode export --src "./LiDAR.zip" --dst "./exportKitti" --fmt kitti
[LiDAR.zip](https://github.com/xtreme1-io/xtreme1/files/14433256/LiDAR.zip)

2. Kitti format:
sailing-yacht 0 0 0 0 0 0 0 11.5 3.0 10.5 -13.1977033 9.76468154 68.57108511 0.27449926
| Values | Name | Description |
|---|---|---|
| 1 |  class | Describes the type of object: 'sailing-yatch', 'motor-boat', 'vessel', 'buoy' or 'DontCare' |
|1 | truncated (unused) | Float from 0 (non-truncated) to 1 (truncated), where truncated refers to the object leaving image boundaries |
| 1 | occluded (unused) | Integer (0,1,2,3) indicating occlusion state: 0 = fully visible, 1 = partly occluded 2 = largely occluded 3 = unknown |
| 1 | alpha (unused) | Observation angle of object, ranging [-pi..pi]
| 4 | bbox (unused) | 2D bounding box of object in the image (0-based index): contains left, top, right, bottom pixel coordinates. |
| 3 | dimensions | 3D object dimensions: height, width, length (in meters) |
| 3 | location | 3D object location x,y,z in camera coordinates (in meters) |
| 1 | rotation_y | Rotation ry around Y-axis in camera coordinates [-pi..pi] |
| 1 | score | Only for results: Float, indicating confidence in detection, needed for p/r curves, higher is better. |

Kind Regards,
Yvan

**Comment by jotamotk** [comment]
Hi Yvan,
We are working on a more universal Kitti format compatible with the scenario that can export results without 2D projection. We will close this issue when it is done. We will keep you posted!

Best,
James

**Comment by jotamotk** [comment]
Hi Yvan,
We have added a KITTI-like export script to our cloud version. You can find it by selecting the data format for export.
For Xtreme1 you can check our [sdk](https://github.com/xtreme1-io/xtreme1-sdk/commit/b47482e7908535bbdc59e52da567cebbf43f001a)

Best,
James

**Comment by e1eustac** [comment]
Hi James,
Thank you for your efficient work. It's seem to be ok.
Regards
Yvan

**Comment by jotamotk** [comment]
Sure
