### ISSUE TITLE
Using VPN to access

### ISSUE THREAD

**Issue by jotamotk** [xtreme1-io/xtreme1#212]
Hi Team, I am trying to use this behind a vpn, which ports do i need to open?
![image](https://github.com/xtreme1-io/xtreme1/assets/10492049/6e04e568-d3b1-4675-82b9-0e74b04426db)

I whitelisted all the ports in the docker ports :8291, 8295, 8192, 8193, 8293, 8294, 8190, 8290 ,but still not able to access

i also see there is no csrftoken, so is there a specific thing i need to allow for htis to happen

**Comment by jaggerwang** [comment]
The only port number for Xtreme1 to provide external services is 8190, while other ports are mapped ports for internal services on the host for developers to debug. It seems that your VPN force checked some http header security policies.

**Comment by aj148** [comment]
I see. Actually I see there is an issue with how the remote address was created. If my address is something like <hostname>.<second level domain>.com. If you have a second level domain the authentication fails
