### ISSUE TITLE
Upload dataset

### ISSUE THREAD

**Issue by aj148** [xtreme1-io/xtreme1#217]
When uploading according to this [doc](https://docs.xtreme1.io/xtreme1-docs/developer-reference/api-document), I had some trouble 

> According to the form file upload format (Content-Type: multipart/form-data), use the PUT method to request the upload address to directly upload the compressed package to the object storage service;

Can you give an idea of how this requests looks like?

also for step 4, how do you know what the dataset id should be?

**Comment by jaggerwang** [comment]
You can using a s3 compatible client sdk (recommend minio) to construct this request, as we use minio as the object storage service. As the dataset id, you can create a new dataset, or query an existing one to get the id.

**Comment by aj148** [comment]
do we have a bucket that exits already within xtreme1? also this looks different than what the sdk has for import

**Comment by jaggerwang** [comment]
Sorry, it's different to upload with minio sdk. We have already and an example for uploading through presigend url in the api doc, https://apifox.com/apidoc/shared-2f8468c3-a269-4e3d-9df7-c589bda69450/api-153037674 .
![image](https://github.com/xtreme1-io/xtreme1/assets/1255011/70f31097-49e8-4500-bb05-96b176b052fb)

**Comment by VeeranjaneyuluToka** [comment]
Hi, Is there away to annotate without uploading the dataset? I mean i wanted to have local copy (in my host machine) and annotate without uploading at all.

**Comment by jaggerwang** [comment]
It is currently not supported, and the dataset management is also part of the Xtreme1 function. What you expect is a pure tool. However, because Xtreme1 is privately deployed in your local machine, so there is no data security problem.
