### ISSUE TITLE
Copy Feature v.09

### ISSUE THREAD

**Issue by MaxPRon** [xtreme1-io/xtreme1#221]
Hi,

I'm using the Xtreme Version 0.9 locally to label a lidar-(fusion) dataset. 

I wanted to ask if there is a copy feature available ? 

It would already be super helpful just be able to simply copy the labels into the next frame. If seen it's possible in the cloud version. In https://github.com/xtreme1-io/xtreme1/issues/100 (March, 2023)  it was mentioned that tracking is not planned to be included in the community version. 

Does this still apply ? Again a simple copy feature without any compensation etc. would already be nice.

Maybe there is also a workaround.

Thanks a lot!

**Comment by MaxPRon** [comment]
Hi :) @jotamotk  Is there any update on that issue ?

**Comment by jotamotk** [comment]
Hi @MaxPRon ,
Sorry to reply to you late. I was otherwise engaged.

Copy features are currently unavailable in Xtreme1 but are planned in the feature. Our new roadmap will include integrating and open-sourcing almost all of the BasicAI cloud toolsets into Xtreme1. 

Due to limited resources, our next priority will be integrating extensive toolsets like text, LiDAR Segmentation, and LLM into Xtreme1 instead of advanced features like copy. So it will probably be late. If you want this feature shortly, any PRs will be appreciated 

Best,
James

**Comment by MaxPRon** [comment]
Hi @jotamotk ,

thanks a lot for the update.

Regarding the feature, I could give it a try but we super helpful if you would be able to give some pointers where in the code I should get started.

I would aim for a simple copy feature with the following funcitonality:

- Button/Check mark to select "copy mode"
- Copy/Merge the existing label (file) with the to/with the one from the next frame

Best,

Max

**Comment by jotamotk** [comment]
Sure, @guhaomine will give you some pointers to start

**Comment by guhaomine** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/45654441/b20e0214-2d0c-4951-9776-b5bba421bc41)
In the point cloud continuous frame data set annotation, we implemented the function of copying the results to the next frame.
In the code, there is a method called "track" that you may need. The file path is
'frontend\pc-tool\src\packages\pc-editor\common\DataManager.ts'
![image](https://github.com/xtreme1-io/xtreme1/assets/45654441/dfba23ec-983b-46f5-b362-1478930affe6)

**Comment by MaxPRon** [comment]
@guhaomine Thanks for the pointer. Another quick question. The screenshot you're showing is from the cloud or community version ?

**Comment by guhaomine** [comment]
@MaxPRon No, the community version has this feature, you need to upload a continuous frame data set. The timeline will be displayed
![image](https://github.com/xtreme1-io/xtreme1/assets/45654441/064738c6-2f5b-4780-8f8d-8120f09a7ea6)

**Comment by chanyoung1998** [comment]
@MaxPRon  is there any update? our team is planning to implement that object tracking function for our own. If you have any update or pregress about it, let me know!

**Comment by MaxPRon** [comment]
@chanyoung1998 Not really, the hint @guhaomine  gave was actually what I was looking for. Although l would still be interested in an object tracking/interpolation feature.

@guhaomine Also thanks a lot for the hint :)

**Comment by chanyoung1998** [comment]
@guhaomine , if you happen to know model request format for Tracking Object ?  I'd like to know http call request format for tracking model.

**Comment by jaggerwang** [comment]
@chanyoung1998 Right now, only object detection models can be customized, the object tracking model is a little complicated, as it need to call the object detection model first, it will be simplified and allow customize in the future.

You can find the related docs [here](https://docs.xtreme1.io/xtreme1-docs/developer-reference/api-document).
![image](https://github.com/xtreme1-io/xtreme1/assets/1255011/57e826c1-dbb7-49bb-8e7d-060c3413a588)
