### ISSUE TITLE
Cannot view or annotate the sample data after uploading

### ISSUE THREAD

**Issue by songkq** [xtreme1-io/xtreme1#222]
@jaggerwang Hi, could you please give some advice for this issue?

**Describe the bug**

**To Reproduce**
```
git clone https://github.com/xtreme1-io/xtreme1.git
cd xtreme1
docker compose up
```

1. Upload dataset:
https://app.box.com/s/v97k7rlrs8oxhz12iz3f3qcgr3p5vukc
2. build the Ontology
<img width="1098" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/30183023/2b90b7bc-f091-489e-8472-96a7a8fd931f">
3. Select a item to view or annotate
<img width="1219" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/30183023/6a416a9f-667a-4710-a958-37a7eb46e25f">
<img width="1508" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/30183023/5c28de22-87cf-4b05-a1fd-70a8dc99a852">

**Expected behavior**
annotate the sample data after uploading.

**Screenshots**
<img width="1498" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/30183023/3d3b9b5a-a9aa-4a29-904f-a19a96b48975">

<img width="1508" alt="image" src="https://github.com/xtreme1-io/xtreme1/assets/30183023/5c28de22-87cf-4b05-a1fd-70a8dc99a852">

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser chrome
 - Version 

**Additional context**

**Comment by songkq** [comment]
@jotamotk @chua1989 Hi, could you please give some advice for this issue? Thanks

**Comment by chua1989** [comment]
@jotamotk Is there development access to the interface after running? For example,/api/user/logged
