### ISSUE TITLE
change docker image

### ISSUE THREAD

**Issue by jotamotk** [xtreme1-io/xtreme1#224]
Can we change docker image ? Or edit content

**Comment by im-shadab** [comment]
How can we modify the Docker Compose file to incorporate changes for all Docker images, including frontend and backend, while ensuring Docker can host the site with updated frontend files?

**Comment by jaggerwang** [comment]
You can refrence this doc [Install from Source](https://docs.xtreme1.io/xtreme1-docs/get-started/install-from-source) to build new images from your local source code.
