### ISSUE TITLE
Annotation on accumulation

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#225]
Hi all,

I'm creating this ticket to discuss about an accumulation feature to help annotate LiDAR data. 

To accumulate data, we need to know the lidar pose in a global frame. I think we could use the lidar_config to register the lidar pose.

We could then load multiple pointclouds in their corresponding frame, and directly annotate multi-frames.

What do you think about this feature ?

**Comment by jotamotk** [comment]
This is an absolutely innovative feature. We are still developing it for our cloud version, and it will be coming soon.

**Comment by ClementLeBihan** [comment]
I've did a first try with a setting Add Accumulation that load more frames and add it in the existing pc ...

![Screenshot from 2024-03-26 09-28-37](https://github.com/xtreme1-io/xtreme1/assets/12940019/c12387cd-cadc-49b1-b074-b95c0c90e1b3)

To do so, I load the lidar_config pose matrix in IFrame lidarExternalPose of each matrix, and I transform the pointcloud of additional frames in the current frame ... I saw there is a worldMatrix in IFrame object, it may be better to use it, I do not know exactlly what is the better way. 
Maybe using the worldMatrix of objects can be easier to display multiple frames ... 
What do you think ?

**Comment by guhaomine** [comment]
You are right, using worldMatrix can easily operate each point cloud. But integrating such functions into tools is not easy, and we are also trying to complete it.

**Comment by jotamotk** [comment]
@ClementLeBihan, this feature is available on our cloud version now, but it is a little laggy when doing a large point cloud calculation.
