### ISSUE TITLE
Point cloud annotation

### ISSUE THREAD

**Issue by HelloHanShan** [xtreme1-io/xtreme1#226]
Can we only annotate point cloud data?

**Comment by jaggerwang** [comment]
Yes, both Lidar (without camera images) and Lidar fusion (with camera images) are supported.

**Comment by VeeranjaneyuluToka** [comment]
What format does it support (.bin, .pcd, .las etcc)?

**Comment by jaggerwang** [comment]
Right now we only support [PCD](https://pointclouds.org/documentation/tutorials/pcd_file_format.html) format, with supporting both ascii and binary.

**Comment by VeeranjaneyuluToka** [comment]
Thanks for quick reply! Is there any guide on how to start annotating custom point cloud dataset as i am newbie here?

**Comment by jotamotk** [comment]
For the Xtreme1 guide, please refer to 
 1. Data upload: https://docs.xtreme1.io/xtreme1-docs/product-guides/upload-dataset
 2. Fusion tool: https://docs.xtreme1.io/xtreme1-docs/product-guides/lidar-annotation-tool

For the BasicAI cloud version, please refer to
 1. Quick start：https://docs.basic.ai/docs/getting-started
 2. Data Upload：https://docs.basic.ai/docs/create-dataset
 5. Fusion tool https://docs.basic.ai/docs/lidar-fusion-tool

**Comment by VeeranjaneyuluToka** [comment]
Thanks again for quick reply! BTW, what is the difference between basic.ai and xtreme?

**Comment by jotamotk** [comment]
The main difference will be workflow and performance. From toolsets currently, Xtreme1 is 5 big versions later than the cloud version, but we are planning and trying to open-source almost all the tools.
