### ISSUE TITLE
Seeking Detailed Information on the Model Architecture and Weight File Used in Basic AI for LiDAR-Camera Fusion Annotation

### ISSUE THREAD

**Issue by jotamotk** [xtreme1-io/xtreme1#230]
Hello, Basic AI Team

I started annotating on the datasets of LiDAR Fusion Trial. I used Basic LiDAR Object Detection model. The results are so good.
I'm wondering that how worked it. So I red your documents and I understood that Lidar-camera Fusion (Frame series) Annotation uses OpenPCDet. That annotates 3D point Cloud. However, I couldn't know which model (architecture) and weight file are used on Basic AI. Could I know the information.

Regards,
Silva

**Comment by ShirleySprite** [comment]
Hello! The detailed configuration of the model can be found in this file: https://github.com/xtreme1-io/point-cloud-object-detection/blob/main/pcdet_open/cfgs/nuscenes_models/cbgs_voxel0075_res3d_centerpoint.yaml

**Comment by silva21d** [comment]
> Hello! The detailed configuration of the model can be found in this file: https://github.com/xtreme1-io/point-cloud-object-detection/blob/main/pcdet_open/cfgs/nuscenes_models/cbgs_voxel0075_res3d_centerpoint.yaml

@ShirleySprite 
Thank you for your answer I confirmed the source code and understand the algorithm.
