### ISSUE TITLE
Status of Dataset does not change appropriately, when DataSet is composed of Scenes.

### ISSUE THREAD

**Issue by chanyoung1998** [xtreme1-io/xtreme1#234]
Hello, Basic AI Team!
I am ChanYoung, big fan of you guys and user.

I started annotating on our own datasets.  It is composed of 10 Scenes, and there are 200 Single Data in the Scene. 
So there are 2000 Single Data.

The problem is that when i submit annotation result of the Scene, there is no change of status of annotation works. 
![image](https://github.com/xtreme1-io/xtreme1/assets/57498298/15946012-0cd4-4eb9-b35c-c1fafded2aa2)

And i found the reason is that `getDatasetStatisticsByDatasetIds` only counts 'SINGLE_DATA' and when `submit` clicked, the Scene is only annotated. 

```xml
    <select id="getDatasetStatisticsByDatasetIds" resultType="ai.basic.x1.adapter.port.dao.mybatis.model.DatasetStatistics">
        SELECT dataset_id AS datasetId,
               SUM(CASE `annotation_status` WHEN 'ANNOTATED' THEN 1 ELSE 0 END) AS annotatedCount,
               SUM(CASE `annotation_status` WHEN 'NOT_ANNOTATED' THEN 1 ELSE 0 END) AS notAnnotatedCount,
               SUM(CASE `annotation_status` WHEN 'INVALID' THEN 1 ELSE 0 END) AS invalidCount
        FROM data WHERE dataset_id in
        <foreach collection="datasetIds" item="datasetId" open="(" separator="," close=")">
            #{datasetId}
        </foreach> AND is_deleted = FALSE AND type = 'SINGLE_DATA'
        GROUP BY dataset_id
    </select>



```

```java
 @Transactional(rollbackFor = Exception.class)
    public void submit(Long itemId) {
        var dataEdit = dataEditUseCase.checkLock(Sets.newHashSet(itemId));
        DataStatusEnum status = Optional.ofNullable(dataInfoDAO.getById(itemId)).orElseThrow().getStatus();
        DataAnnotationStatusEnum annotationStatus = DataAnnotationStatusEnum.INVALID;
        if (DataStatusEnum.VALID.equals(status)) {
            annotationStatus = DataAnnotationStatusEnum.ANNOTATED;
        }
        dataInfoDAO.updateById(DataInfo.builder().id(itemId).annotationStatus(annotationStatus).build());
        var sceneId = dataEdit.getSceneId();
        if (ObjectUtil.isNotNull(sceneId) && DataStatusEnum.INVALID.equals(status)) {
            dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.INVALID).build());
        } else if (ObjectUtil.isNotNull(sceneId) &&  DataStatusEnum.VALID.equals(status)) {
            var lambdaQueryWrapper = Wrappers.lambdaQuery(DataInfo.class);
            lambdaQueryWrapper.eq(DataInfo::getDatasetId, dataEdit.getDatasetId());
            lambdaQueryWrapper.eq(DataInfo::getParentId, sceneId);
            lambdaQueryWrapper.eq(DataInfo::getStatus, DataStatusEnum.INVALID);
            if (dataInfoDAO.count() == 0) {
                dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.ANNOTATED).build());
            } else {
                dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.INVALID).build());
            }
       
        }
    }

```

## Suggestion
and I carefully suggest this code. 

```java
    @Transactional(rollbackFor = Exception.class)
    public void submit(Long itemId) {
        var dataEdit = dataEditUseCase.checkLock(Sets.newHashSet(itemId));
        DataStatusEnum status = Optional.ofNullable(dataInfoDAO.getById(itemId)).orElseThrow().getStatus();
        DataAnnotationStatusEnum annotationStatus = DataAnnotationStatusEnum.INVALID;
        if (DataStatusEnum.VALID.equals(status)) {
            annotationStatus = DataAnnotationStatusEnum.ANNOTATED;
        }
        dataInfoDAO.updateById(DataInfo.builder().id(itemId).annotationStatus(annotationStatus).build());
        var sceneId = dataEdit.getSceneId();
        if (ObjectUtil.isNotNull(sceneId) && DataStatusEnum.INVALID.equals(status)) {
            dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.INVALID).build());
        } else if (ObjectUtil.isNotNull(sceneId) &&  DataStatusEnum.VALID.equals(status)) {
            var lambdaQueryWrapper = Wrappers.lambdaQuery(DataInfo.class);
            lambdaQueryWrapper.eq(DataInfo::getDatasetId, dataEdit.getDatasetId());
            lambdaQueryWrapper.eq(DataInfo::getParentId, sceneId);
            lambdaQueryWrapper.eq(DataInfo::getStatus, DataStatusEnum.INVALID);
            if (dataInfoDAO.count() == 0) {
                dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.ANNOTATED).build());
            } else {
                dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.INVALID).build());
            }
            // When Scene is submitted, SingleData of the Scene is also annotated.
            var dataInfoLambdaUpdateWrapper = Wrappers.lambdaUpdate(DataInfo.class)
                    .eq(DataInfo::getDatasetId, dataEdit.getDatasetId())
                    .eq(DataInfo::getParentId, sceneId)
                    .eq(DataInfo::getStatus, DataStatusEnum.VALID);
            dataInfoLambdaUpdateWrapper.set(DataInfo::getAnnotationStatus, DataAnnotationStatusEnum.ANNOTATED);
            dataInfoDAO.update(dataInfoLambdaUpdateWrapper);

           var dataInfoLambdaUpdateWrapper2 = Wrappers.lambdaUpdate(DataInfo.class)
                    .eq(DataInfo::getDatasetId, dataEdit.getDatasetId())
                    .eq(DataInfo::getParentId, sceneId)
                    .eq(DataInfo::getStatus, DataStatusEnum.INVALID);
            dataInfoLambdaUpdateWrapper2.set(DataInfo::getAnnotationStatus, DataAnnotationStatusEnum.INVALID);
            dataInfoDAO.update(dataInfoLambdaUpdateWrapper2);

        }
    }
```

When you have some free time, Please take a look 🙇‍♂️.
 And i also want to contribute xtreme1. 
If you think this issue is acceptable, plz assign this issue to me.!

**Comment by fanyinbo** [comment]
Thank you, I found a bit of logic error in the code. The logic of the continuous frame is that if there is a data status of INVALID in the continuous frame, the entire continuous frame is INVALID. After submission, if the continuous frame status is INVALID, it is necessary to update the data annotation status of the INVALID data in the continuous frame to INVALID, and the status of VALID to ANNOTATED. If the continuous frame status is VALID, it is necessary to update the continuous frame and all the data annotation status under the continuous frame to ANNOTATED.

@Transactional(rollbackFor = Exception.class)
    public void submit(Long itemId) {
        var dataEdit = dataEditUseCase.checkLock(Sets.newHashSet(itemId));
        DataStatusEnum status = Optional.ofNullable(dataInfoDAO.getById(itemId)).orElseThrow().getStatus();
        DataAnnotationStatusEnum annotationStatus = DataAnnotationStatusEnum.INVALID;
        if (DataStatusEnum.VALID.equals(status)) {
            annotationStatus = DataAnnotationStatusEnum.ANNOTATED;
        }
        var sceneId = dataEdit.getSceneId();
        if (ObjectUtil.isNull(sceneId)) {
            dataInfoDAO.updateById(DataInfo.builder().id(itemId).annotationStatus(annotationStatus).build());
        }else if (ObjectUtil.isNotNull(sceneId) && DataStatusEnum.INVALID.equals(status)) {
            dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.INVALID).build());
            // When Scene is submitted, SingleData of the Scene is also annotated.
            var dataInfoLambdaUpdateWrapper = Wrappers.lambdaUpdate(DataInfo.class)
                    .eq(DataInfo::getDatasetId, dataEdit.getDatasetId())
                    .eq(DataInfo::getParentId, sceneId)
                    .eq(DataInfo::getStatus, DataStatusEnum.VALID);
            dataInfoLambdaUpdateWrapper.set(DataInfo::getAnnotationStatus, DataAnnotationStatusEnum.ANNOTATED);
            dataInfoDAO.update(dataInfoLambdaUpdateWrapper);

            var dataInfoLambdaUpdateWrapper2 = Wrappers.lambdaUpdate(DataInfo.class)
                    .eq(DataInfo::getDatasetId, dataEdit.getDatasetId())
                    .eq(DataInfo::getParentId, sceneId)
                    .eq(DataInfo::getStatus, DataStatusEnum.INVALID);
            dataInfoLambdaUpdateWrapper2.set(DataInfo::getAnnotationStatus, DataAnnotationStatusEnum.INVALID);
            dataInfoDAO.update(dataInfoLambdaUpdateWrapper2);
        }else if (ObjectUtil.isNotNull(sceneId) &&  DataStatusEnum.VALID.equals(status)) {
            dataInfoDAO.updateById(DataInfo.builder().id(sceneId).annotationStatus(DataAnnotationStatusEnum.ANNOTATED).build());
            var dataInfoLambdaUpdateWrapper = Wrappers.lambdaUpdate(DataInfo.class)
                    .eq(DataInfo::getDatasetId, dataEdit.getDatasetId())
                    .eq(DataInfo::getParentId, sceneId);
            dataInfoLambdaUpdateWrapper.set(DataInfo::getAnnotationStatus, DataAnnotationStatusEnum.ANNOTATED);
            dataInfoDAO.update(dataInfoLambdaUpdateWrapper);
        }
    }
    
    Please submit the modified Merge Request (MR), and we will merge it. Thank you for your contribution.
