### ISSUE TITLE
the bounding box of object is not parrell to ground

### ISSUE THREAD

**Issue by yangpanquan** [xtreme1-io/xtreme1#236]
Hi, Thanks for your amazing work! 
    When I use the version of online, I get some troubles that the bounding boxes of results are not parrell to ground.
My lidar coordinate system is not parallel to the ground.It has an inclination angle with the ground. As you can see the below picture. So, what can I do to get right detection result when I use online annotation tool  or  use this project?
    By the way,  the bounding boxes are annotated by the pretraining model in the online version.

![annotation_result](https://github.com/xtreme1-io/xtreme1/assets/68114558/e14e1bd6-8574-4399-8d7d-c3741041b8b1)

**Comment by jaggerwang** [comment]
Right now the object dectection model not support inclination angle with the ground, but you can adjust the inclination angle of annotation object by the three views in the tool.

**Comment by yangpanquan** [comment]
Thank you! I get it!
