### ISSUE TITLE
pre-labeling loading on lidar space

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [xtreme1-io/xtreme1#237]
I have point clouds are in pcd format and labels are in .json files and i created folder structure as follows
    Lidar_samples:
	    - lidar_point_cloud_0:
		    000000.pcd
		    000001.pcd etc..
	    - result:
		    000000.json
		    000001.json etc.. 

and json content format is as follows
      [
          {
              "version": "Xtreme1 V0.6",
              "dataId": 0,
              "sourceName": "Ground Truth",
              "classificationValues": "null",
              "objects": [
                  {
                      "id": 0,
                      "type": "3D_Box",
                      "classId": 4,
                      "className": "pb",
                      "trackId": "xvdfdsf",
                      "trackName": "3",
                      "classValues": [],
                      "contour": {
                          "pointN": 20,
                          "points": [],
                          "size3D": {
                              "x": 12.828439712524414,
                              "y": 9.704872131347656,
                              "z": 21.630416870117188
                          },
                          "center3D": {
                              "x": -56.76114273071289,
                              "y": -82.24117279052734,
                              "z": -2.216766357421875
                          },
                          "rotation3D": {
                              "x": 0.0,
                              "y": 0.0,
                              "z": -0.003778637619689107
                          },
                          "viewIndex": 0
                      },
                      "modelConfidence": "null",
                      "modelClass": ""
                  }
              ]
          }
      ]

But when i upload, i can not see these labels drawn on the point cloud. I selected checkbox when uploading as follows
![image](https://github.com/xtreme1-io/xtreme1/assets/61545398/82584d90-5ee8-4e33-982d-7a21db976530)

is there anything wrong in my json content format or missing anything else? Thanks!

**Comment by jaggerwang** [comment]
Please give us an example zip file, so we can figure out the reason.

**Comment by VeeranjaneyuluToka** [comment]
@jaggerwang , thanks for getting back to me! Attached a few samples for your reference
[lidar_samples_shared.zip](https://github.com/xtreme1-io/xtreme1/files/15033720/lidar_samples_shared.zip)
Hope you will get back to me asap. Thanks!

**Comment by fanyinbo** [comment]
The type in the result file is wrong, it should be 3D_BOX

**Comment by VeeranjaneyuluToka** [comment]
Yes, that works. Thanks!
