### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by dakshbhaumik** [xtreme1-io/xtreme1#242]
**Is your feature request related to a problem? Please describe.**
A 90-century-school-work-style UI design

**Describe the solution you'd like**
I have re-design the Xtreme1 UI based on the Cloud Version: Please see here:
https://www.figma.com/design/dAVkxZf4TzLtLRAmNReuiv/Xtreme1-UI-refactor?node-id=0-1&t=A5ExD6u8QaAmyXMW-1

**Additional context**
Is there any chance of creating a branch for the design?

**Comment by jotamotk** [comment]
Very nice design!!  Can I have an edit access to it?

**Comment by jotamotk** [comment]
Thanks for your contribution, Daksh! Now the UI link changed to https://www.figma.com/design/dAVkxZf4TzLtLRAmNReuiv/Xtreme1-UI-refactor?node-id=0-1&t=A5ExD6u8QaAmyXMW-1
