### ISSUE TITLE
Creating same dataset type multiple times with result

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [xtreme1-io/xtreme1#243]
**Describe the bug**
Created two datasets with same dataset type for example : "Lidar Fusion" with GTs in result folder, but can not see GT in second dataset

**To Reproduce**
1. create two datasets with dataset type "Lidar Fusion", both having lidar pcds and result (GTs)
2. Upload and create Ontology
3. try view/annotate
4. It does not show GTs

**Expected behavior**
It should show annotation when we created with mulitple dataset with same dataset type

**Comment by jaggerwang** [comment]
Please give some screenshots or example zip package for us to verify.

**Comment by jaggerwang** [comment]
I still don't quite understand what you're saying, you create two lidar fusion dataset and upload lidar data with result, and the result both drawn on point cloud, so where is the problem?

**Comment by VeeranjaneyuluToka** [comment]
Result drawn on first one only not on second one. I believe result should be drawn on both, is n ot it?

**Comment by jaggerwang** [comment]
Yes, it should be display on both datasets, each dataset is independent of each other. Can you supply the example zip package of your senond dataset?

**Comment by jaggerwang** [comment]
Closed as no further feedback.
