### ISSUE TITLE
the default values for camera calibration

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#244]
Hi, thank you for the work.

I can't find the camera calibration function, so I'm trying to perform the camera calibration.

**[workflows]**
1. Get the `config` value in `loadFameConfig`.
2. Calculate the matrix using `deg step`, `t step`, `fxfy scale`, `xyz degree`, `xyz trans` fields. in `setOptions`
3. Call `setOptions` and re-render every time the value of "2." changes

What should I specify as the default values of  camera_internal, camera_external from config in loadFameConfig?
ex) deg_step = 0.3 ... etc

Can you help me with the above?

 I am willing to contribute to the development of these features if they align with Xtreme's development roadmap.

**Comment by jaggerwang** [comment]
For more info about camera configs, you can refer the BasicAI Cloud's doc 
[Point cloud camera configs](https://docs.basic.ai/docs/annotated-data-format-1#point-cloud-camera-configs).

**Comment by seungdeok** [comment]
@jaggerwang 
Thanks, I found the answer I was looking for in the above document.
