### ISSUE TITLE
How to render a point cloud in a single image view

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#245]
Hi, thanks for your work.

I am trying to do point cloud rendering in a single image view.
Is there any way to render the point cloud from the main view in a single image view for each photo image view?

**Comment by jaggerwang** [comment]
You mean render the point cloud in the image view? Why you need to do this?

**Comment by seungdeok** [comment]
@jaggerwang 
Thank you for your feedback.

Yes, My intention is equal what you said.
I want to make the function as module to filter only the point cloud area of each image view in the Main View.

**Comment by jaggerwang** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/1255011/c24aad56-008b-4dd7-9aab-3e4871e7ed81)

You can check / uncheck the eye icon on the top right corner of each image view to highlight (white color) the points contained in this view, does this feature is what your need?

**Comment by seungdeok** [comment]
Yes, this is what I need.
