### ISSUE TITLE
how to convert this calibration file?

### ISSUE THREAD

**Issue by aubeena007** [xtreme1-io/xtreme1#247]
################################################################################
Notes

* Coordinate system: X = driving direction, Y = left direction, Z = Upwards
* XY plane is the top of the rails with Z=0. This fixes three of the six DoF (degrees of freedom) of the reference coordinate system.

################################################################################
CAMERA
data_folder: ir_left
position: [0.0788369, 0.426123, 3.523]
rotation_quaternion (w,x,y,z): [0.996027, -0.000591278, 0.0222156, 0.0862389]
rotation matrix:
[0.984138642741182, -0.1718187119796004, 0.04415271313537852;
 0.171766169581505, 0.9851250110146101, 0.005009556942691675;
 -0.04435667763529644, 0.002653843841579718, 0.9990122332894742]
angle axis rotation: [-0.00118412, 0.0444902, 0.172707]
homogeneous transform:
[0.984138642741182, -0.1718187119796004, 0.04415271313537852, 0.07883686949160869;
 0.171766169581505, 0.9851250110146101, 0.005009556942691675, 0.4261232192792224;
 -0.04435667763529644, 0.002653843841579718, 0.9990122332894742, 3.523;
 0, 0, 0, 1]
measured_position: [0, 0, 0]
camera_matrix: [3535.294117647, 0, 319.5;
 0, 3535.294117647, 239.5;
 0, 0, 1]
dist_coeffs: [0, 0, 0, 0, 0]

################################################################################
CAMERA
data_folder: ir_center
position: [0.0961069, 0.25265, 3.5225]
rotation_quaternion (w,x,y,z): [0.999709, 0.00411229, 0.0227947, 0.00666547]
rotation matrix:
[0.9988719430073834, -0.01313958855431502, 0.0456310495745843;
 0.0135145432523949, 0.9998773211011482, -0.007918324839901441;
 -0.04552140807723332, 0.008526075311323874, 0.9989269780351573]
angle axis rotation: [0.00822539, 0.0455939, 0.0133322]
homogeneous transform:
[0.9988719430073834, -0.01313958855431502, 0.0456310495745843, 0.09610688748423474;
 0.0135145432523949, 0.9998773211011482, -0.007918324839901441, 0.2526498885376692;
 -0.04552140807723332, 0.008526075311323874, 0.9989269780351573, 3.522499999999999;
 0, 0, 0, 1]
measured_position: [0, 0, 0]
camera_matrix: [3535.294117647, 0, 319.5;
 0, 3535.294117647, 239.5;
 0, 0, 1]
dist_coeffs: [0, 0, 0, 0, 0]

################################################################################
CAMERA
data_folder: ir_right
position: [0.0828754, 0.0801291, 3.5235]
rotation_quaternion (w,x,y,z): [0.99716, 0.00074111, 0.0222082, -0.0719592]
rotation matrix:
[0.9886573221435483, 0.1435426798446681, 0.0441836896938154;
 -0.1434768448618926, 0.9896426359875975, -0.004674186987738497;
 -0.04439700846256057, -0.001718167201129793, 0.9990124891817141]
angle axis rotation: [0.00148362, 0.0444586, -0.144055]
homogeneous transform:
[0.9886573221435483, 0.1435426798446681, 0.0441836896938154, 0.08287538600086802;
 -0.1434768448618926, 0.9896426359875975, -0.004674186987738497, 0.0801290858254784;
 -0.04439700846256057, -0.001718167201129793, 0.9990124891817141, 3.523499999999999;
 0, 0, 0, 1]
measured_position: [0, 0, 0]
camera_matrix: [3535.294117647, 0, 319.5;
 0, 3535.294117647, 239.5;
 0, 0, 1]
dist_coeffs: [0, 0, 0, 0, 0]

################################################################################
CAMERA
data_folder: rgb_highres_left
position: [0.0559156, 0.20323, 2.07979]
rotation_quaternion (w,x,y,z): [0.981614, -0.00288816, -0.00186774, 0.190846]
rotation matrix:
[0.9271485473493668, -0.3746636170289103, -0.004769195191337372;
 0.3746851944165804, 0.9271388413122352, 0.004957218495839745;
 0.002564416691634481, -0.006383024754788097, 0.9999763401011104]
angle axis rotation: [-0.00581199, -0.00375855, 0.384049]
homogeneous transform:
[0.9271485473493668, -0.3746636170289103, -0.004769195191337372, 0.05591560352572743;
 0.3746851944165804, 0.9271388413122352, 0.004957218495839745, 0.203229646692153;
 0.002564416691634481, -0.006383024754788097, 0.9999763401011104, 2.079787150472212;
 0, 0, 0, 1]
measured_position: [0.086166, 0.214634, 2.0785]
camera_matrix: [7265.09513308939, 0, 2099.699693520321;
 0, 7265.09513308939, 1443.142658090831;
 0, 0, 1]
dist_coeffs: [-0.0878118, 0.0196239, 0, 0, 0.902557]
combined homogenous transform:
[0.9271485473493668, -0.3746636170289103, -0.004769195191337372, 0.05591560352572743;
 0.3746851944165804, 0.9271388413122352, 0.004957218495839745, 0.203229646692153;
 0.002564416691634481, -0.006383024754788097, 0.9999763401011104, 2.079787150472212;
 0, 0, 0, 1]

################################################################################
CAMERA
data_folder: rgb_highres_center
position: [0.044216, 0.00122755, 2.07848]
rotation_quaternion (w,x,y,z): [0.99999, -0.00102792, -0.000853255, 0.0042645]
rotation matrix:
[0.9999621719218765, -0.008527168633861885, -0.001715261021946117;
 0.00853067694888426, 0.999961514770642, 0.002048542993746481;
 0.001697726738170886, -0.00206309783896331, 0.9999964306692448]
angle axis rotation: [-0.00205585, -0.00170652, 0.00852904]
homogeneous transform:
[0.9999621719218765, -0.008527168633861885, -0.001715261021946117, 0.04421604784634205;
 0.00853067694888426, 0.999961514770642, 0.002048542993746481, 0.00122754853356305;
 0.001697726738170886, -0.00206309783896331, 0.9999964306692448, 2.078480448887938;
 0, 0, 0, 1]
measured_position: [0.0914991, 0.000642412, 2.0785]
camera_matrix: [7267.95450880415, 0, 2056.049238502414;
 0, 7267.95450880415, 1486.862908875167;
 0, 0, 1]
dist_coeffs: [-0.0764891, -0.188057, 0, 0, 1.78279]
combined homogenous transform:
[0.9999621719218765, -0.008527168633861885, -0.001715261021946117, 0.04421604784634205;
 0.00853067694888426, 0.999961514770642, 0.002048542993746481, 0.00122754853356305;
 0.001697726738170886, -0.00206309783896331, 0.9999964306692448, 2.078480448887938;
 0, 0, 0, 1]

################################################################################
CAMERA
data_folder: rgb_highres_right
position: [0.0446595, -0.198137, 2.07807]
rotation_quaternion (w,x,y,z): [0.981743, 0.0141233, 0.0014345, -0.189682]
rotation matrix:
[0.9280376522261472, 0.372477728469156, -0.002541229040898315;
 -0.3723966894366944, 0.9276428352266736, -0.02827500573313209;
 -0.00817445699547013, 0.02718661521918767, 0.9995969518789826]
angle axis rotation: [0.0284197, 0.00288658, -0.381689]
homogeneous transform:
[0.9280376522261472, 0.372477728469156, -0.002541229040898315, 0.04465949163230119;
 -0.3723966894366944, 0.9276428352266736, -0.02827500573313209, -0.1981373107218908;
 -0.00817445699547013, 0.02718661521918767, 0.9995969518789826, 2.078072097109307;
 0, 0, 0, 1]
measured_position: [0.0883353, -0.215363, 2.078]
camera_matrix: [7265.854580654392, 0, 2093.506452810741;
 0, 7265.854580654392, 1482.255759518024;
 0, 0, 1]
dist_coeffs: [-0.0655375, -0.329857, 0, 0, 2.48002]
combined homogenous transform:
[0.9280376522261472, 0.372477728469156, -0.002541229040898315, 0.04465949163230119;
 -0.3723966894366944, 0.9276428352266736, -0.02827500573313209, -0.1981373107218908;
 -0.00817445699547013, 0.02718661521918767, 0.9995969518789826, 2.078072097109307;
 0, 0, 0, 1]

################################################################################
CAMERA
data_folder: rgb_left
position: [0.0529804, -0.104374, 3.50403]
rotation_quaternion (w,x,y,z): [0.977521, -0.0108971, 0.0530686, 0.203761]
rotation matrix:
[0.9113306193756673, -0.3995171079359454, 0.09931053647453862;
 0.3972039298751632, 0.9167256823008546, 0.04293089216122715;
 -0.1081921451866488, 0.0003222988220563764, 0.9941299491733363]
angle axis rotation: [-0.021959, 0.10694, 0.410603]
homogeneous transform:
[0.9113306193756673, -0.3995171079359454, 0.09931053647453862, 0.05298038583357811;
 0.3972039298751632, 0.9167256823008546, 0.04293089216122715, -0.1043738398525789;
 -0.1081921451866488, 0.0003222988220563764, 0.9941299491733363, 3.504031915764986;
 0, 0, 0, 1]
measured_position: [0.0851408, -0.0903676, 3.499]
camera_matrix: [4622.041473915607, 0, 1233.380196060109;
 0, 4622.041473915607, 843.3909933480334;
 0, 0, 1]
dist_coeffs: [-0.0868757, 0.53867, 0, 0, 1.69009]
combined homogenous transform:
[0.9113306193756673, -0.3995171079359454, 0.09931053647453862, 0.05298038583357811;
 0.3972039298751632, 0.9167256823008546, 0.04293089216122715, -0.1043738398525789;
 -0.1081921451866488, 0.0003222988220563764, 0.9941299491733363, 3.504031915764986;
 0, 0, 0, 1]

################################################################################
CAMERA
data_folder: rgb_center
position: [0.0539935, -0.285891, 3.50629]
rotation_quaternion (w,x,y,z): [0.998699, 0.00136084, 0.0508077, 0.00420149]
rotation matrix:
[0.994801848338136, -0.008253767163616355, 0.1014946199098106;
 0.008530331054488222, 0.9999609911792882, -0.002291194412618652;
 -0.101471749739171, 0.00314506714465518, 0.9948334496575426]
angle axis rotation: [0.00272285, 0.10166, 0.00840663]
homogeneous transform:
[0.994801848338136, -0.008253767163616355, 0.1014946199098106, 0.05399349045425253;
 0.008530331054488222, 0.9999609911792882, -0.002291194412618652, -0.2858909428211028;
 -0.101471749739171, 0.00314506714465518, 0.9948334496575426, 3.506285581367224;
 0, 0, 0, 1]
measured_position: [0.0904466, -0.28686, 3.5015]
camera_matrix: [4609.471892628096, 0, 1257.158605934;
 0, 4609.471892628096, 820.0498076210201;
 0, 0, 1]
dist_coeffs: [-0.0914603, 0.605326, 0, 0, 0.417134]
combined homogenous transform:
[0.994801848338136, -0.008253767163616355, 0.1014946199098106, 0.05399349045425253;
 0.008530331054488222, 0.9999609911792882, -0.002291194412618652, -0.2858909428211028;
 -0.101471749739171, 0.00314506714465518, 0.9948334496575426, 3.506285581367224;
 0, 0, 0, 1]

################################################################################
CAMERA
data_folder: rgb_right
position: [0.069267, -0.473245, 3.50347]
rotation_quaternion (w,x,y,z): [0.978878, 0.0199065, 0.0472423, -0.197916]
rotation matrix:
[0.9171949079165774, 0.3893517584999271, 0.08460915461648204;
 -0.3855900509340331, 0.9208660346223098, -0.05767199406707697;
 -0.1003683890106395, 0.02027201104966326, 0.9947438022201555]
angle axis rotation: [0.0400957, 0.0951554, -0.398643]
homogeneous transform:
[0.9171949079165774, 0.3893517584999271, 0.08460915461648204, 0.06926700034254044;
 -0.3855900509340331, 0.9208660346223098, -0.05767199406707697, -0.4732449698305176;
 -0.1003683890106395, 0.02027201104966326, 0.9947438022201555, 3.503470643147001;
 0, 0, 0, 1]
measured_position: [0.0922524, -0.483357, 3.5]
camera_matrix: [4613.465257442901, 0, 1230.818284106724;
 0, 4613.465257442901, 783.2495217495479;
 0, 0, 1]
dist_coeffs: [-0.0888195, 0.52648, 0, 0, 1.27408]
combined homogenous transform:
[0.9171949079165774, 0.3893517584999271, 0.08460915461648204, 0.06926700034254044;
 -0.3855900509340331, 0.9208660346223098, -0.05767199406707697, -0.4732449698305176;
 -0.1003683890106395, 0.02027201104966326, 0.9947438022201555, 3.503470643147001;
 0, 0, 0, 1]

################################################################################
LIDAR merged from 6 Devices
data_folder: lidar
position: [0, 0, 0]
rotation_quaternion (w,x,y,z): [1, 0, 0, 0]

################################################################################
RADAR
Rotation around Z in degrees: -0.331005
data_folder: radar
position: [-0.00750583, 0.324989, 1.564]
rotation_quaternion (w,x,y,z): [0.999996, 0, 0, -0.00288856]
rotation matrix:
[0.9999833124708311, 0.00577709095168683, 0;
 -0.00577709095168683, 0.9999833124708311, -0;
 -0, 0, 1]
angle axis rotation: [0, 0, -0.00577712]
homogeneous transform:
[0.9999833124708311, 0.00577709095168683, 0, -0.007505827484708065;
 -0.00577709095168683, 0.9999833124708311, -0, 0.3249887114254094;
 -0, 0, 1, 1.563999999999999;
 0, 0, 0, 1]
################################################################################

**Comment by aubeena007** [comment]
also i have this information too

`"streams": {
      "ir_center": {
        "type": "camera",
        "uri": "ir_center",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              3535.294117647, 0.0, 319.5, 0.0, 0.0, 3535.294117647, 239.5, 0.0,
              0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [0.0, 0.0, 0.0, 0.0, 0.0],
            "width_px": 640,
            "height_px": 480
          }
        }
      },
      "ir_left": {
        "type": "camera",
        "uri": "ir_left",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              3535.294117647, 0.0, 319.5, 0.0, 0.0, 3535.294117647, 239.5, 0.0,
              0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [0.0, 0.0, 0.0, 0.0, 0.0],
            "width_px": 640,
            "height_px": 480
          }
        }
      },
      "ir_right": {
        "type": "camera",
        "uri": "ir_right",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              3535.294117647, 0.0, 319.5, 0.0, 0.0, 3535.294117647, 239.5, 0.0,
              0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [0.0, 0.0, 0.0, 0.0, 0.0],
            "width_px": 640,
            "height_px": 480
          }
        }
      },
      "lidar": { "type": "lidar", "uri": "lidar" },
      "radar": {
        "type": "radar",
        "uri": "radar",
        "stream_properties": {
          "intrinsics_radar": {
            "resolution_px_per_m": 2.857,
            "width_px": 2856,
            "height_px": 1428
          }
        }
      },
      "rgb_center": {
        "type": "camera",
        "uri": "rgb_center",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              4609.471892628096, 0.0, 1257.158605934, 0.0, 0.0,
              4609.471892628096, 820.0498076210201, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0914603, 0.605326, 0.0, 0.0, 0.417134],
            "width_px": 2464,
            "height_px": 1600
          }
        }
      },
      "rgb_highres_center": {
        "type": "camera",
        "uri": "rgb_highres_center",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              7267.95450880415, 0.0, 2056.049238502414, 0.0, 0.0,
              7267.95450880415, 1232.862908875167, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0764891, -0.188057, 0.0, 0.0, 1.78279],
            "width_px": 4112,
            "height_px": 2504
          }
        }
      },
      "rgb_highres_left": {
        "type": "camera",
        "uri": "rgb_highres_left",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              7265.09513308939, 0.0, 2099.699693520321, 0.0, 0.0,
              7265.09513308939, 1217.709330768128, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0878118, 0.0196239, 0.0, 0.0, 0.902557],
            "width_px": 4112,
            "height_px": 2504
          }
        }
      },
      "rgb_highres_right": {
        "type": "camera",
        "uri": "rgb_highres_right",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              7265.854580654392, 0.0, 2093.506452810741, 0.0, 0.0,
              7265.854580654392, 1228.255759518024, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0655375, -0.329857, 0.0, 0.0, 2.48002],
            "width_px": 4112,
            "height_px": 2504
          }
        }
      },
      "rgb_left": {
        "type": "camera",
        "uri": "rgb_left",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              4622.041473915607, 0.0, 1233.380196060109, 0.0, 0.0,
              4622.041473915607, 843.3909933480334, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0868757, 0.53867, 0.0, 0.0, 1.69009],
            "width_px": 2464,
            "height_px": 1600
          }
        }
      },
      "rgb_right": {
        "type": "camera",
        "uri": "rgb_right",
        "stream_properties": {
          "intrinsics_pinhole": {
            "camera_matrix": [
              4613.465257442901, 0.0, 1230.818284106724, 0.0, 0.0,
              4613.465257442901, 783.2495217495479, 0.0, 0.0, 0.0, 1.0, 0.0
            ],
            "distortion_coeffs": [-0.0888195, 0.52648, 0.0, 0.0, 1.27408],
            "width_px": 2464,
            "height_px": 1600
          }
        }
      }
    },
    "coordinate_systems": {
      "ir_center": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0933424, 0.225241, 3.5171],
          "quaternion": [0.00329686, 0.0243397, 0.00187897, 0.999697]
        }
      },
      "ir_left": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0907818, 0.398344, 3.5168],
          "quaternion": [-2.43881e-5, 0.0254277, 0.0822105, 0.996291]
        }
      },
      "ir_right": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0910011, 0.0528333, 3.5176],
          "quaternion": [-0.000112887, 0.025241, -0.0733026, 0.99699]
        }
      },
      "lidar": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0, 0.0, 0.0],
          "quaternion": [0.0, 0.0, 0.0, 1.0]
        }
      },
      "radar": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [-0.0029401, 0.329699, 1.5638],
          "quaternion": [0.0, 0.0, 0.0107221, 0.999943]
        }
      },
      "rgb_center": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0669458, -0.000911152, 2.05432],
          "quaternion": [0.00193374, -0.00293566, 0.00271082, 0.99999]
        }
      },
      "rgb_highres_center": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0801578, -0.332862, 3.50982],
          "quaternion": [-0.00313306, 0.0562995, 0.00482918, 0.998397]
        }
      },
      "rgb_highres_left": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0609096, -0.136682, 3.51522],
          "quaternion": [-0.0121052, 0.0606543, 0.188524, 0.980119]
        }
      },
      "rgb_highres_right": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0510683, -0.525541, 3.51628],
          "quaternion": [0.0217394, 0.0639103, -0.182324, 0.980918]
        }
      },
      "rgb_left": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.0298925, 0.186612, 2.05637],
          "quaternion": [0.00228435, -0.0104673, 0.173904, 0.984704]
        }
      },
      "rgb_right": {
        "type": "sensor",
        "parent": "base",
        "pose_wrt_parent": {
          "translation": [0.051346, -0.196979, 2.05803],
          "quaternion": [0.00740182, -0.0113748, -0.184053, 0.982823]
        }
      },
      "base": {
        "type": "local",
        "parent": "",
        "children": [
          "ir_center",
          "ir_left",
          "ir_right",
          "lidar",
          "radar",
          "rgb_center",
          "rgb_highres_center",
          "rgb_highres_left",
          "rgb_highres_right",
          "rgb_left",
          "rgb_right"
        ]
      }
    },`

**Comment by jaggerwang** [comment]
You can reference this issue #244 .

**Comment by aubeena007** [comment]
@jaggerwang Hey there! Mind explaining how to convert the data above?

**Comment by ShirleySprite** [comment]
![d8974b786f22e80bc84a437a71b07155](https://github.com/xtreme1-io/xtreme1/assets/108784156/853d8225-c9f2-4ab6-b808-eace2d1dc32d)
