### ISSUE TITLE
Load Resource Error

### ISSUE THREAD

**Issue by sayyedasif444** [xtreme1-io/xtreme1#248]
**Describe the bug**
Large LiDAR dataset above 800 mb, does not get extracted in backend on low configuration servers (4 core, 8GB) hence giving error on PC-tool as the file was not found. Once the Server capacity is increased it works file on uploading but the PC-tool UI fails to load the data stating the same error message 'Load Resource Error'

**To Reproduce**
1. Go to LiDAR data tool
2. Upload a large LiDAR dataset
3. Once the upload is complete, click on annotation tool to load the data in pc-tool.
4. pc-tool will open new tab and throws the error

**Expected behavior**
System specification should be mentioned to process the LiDAR data and data should be loaded in PC-TOOL for viewing or annotating

**Screenshots**
![image](https://github.com/xtreme1-io/xtreme1/assets/59442704/32af0f0e-3f1c-404c-a2ec-652f94cf075b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 124.0.6367.119

**Comment by jaggerwang** [comment]
Which version are you using? Please try the latest version.

**Comment by jaggerwang** [comment]
We can successfully upload a lidar fusion package more than 2GB in our test environment, which have 4GB memory limit,   it will consume about 3GB memory to process this package.
