### ISSUE TITLE
Seeking Detailed Information on the Model Architecture and Weight File Used in Basic AI for AI-assisted Boxing (Cuboid) function

### ISSUE THREAD

**Issue by silva21d** [xtreme1-io/xtreme1#250]
Hello, Basic AI Team

Thank you for [answering my question](https://github.com/xtreme1-io/xtreme1/issues/230).

While using your application,  I am curious about a function. I want to ask you one more question.

I use [AI-assisted Boxing function](https://docs.basic.ai/docs/object-detection-tracking#cuboid) to add cuboids. The assist is so fast. I am curious how the function is implemented in your source code and want to know how AI-assisted Boxing works. Could I see the source code and algorithm on your open source? Moreover, if the algorithm is machine learning, I want to know the architecture and the weights.

**Comment by guhaomine** [comment]
The file directory is in frontend \pc-tool\src\packages\pc-editor\utils\AIBox, that is javascript code.

**Comment by silva21d** [comment]
@guhaomine 
Thank you for your reply.

I read the code. All of AI-assisted Boxing is processed in the front end.
How about AB3DMOT (3D Fusion Object Tracking Annotation)?

Could I know the the source code and algorithm on your open source? And I want to know the architecture and the weights if that is machine learning.

**Comment by guhaomine** [comment]
@silva21d We do not have open source 3D Fusion Object Tracking Annotation.
