### ISSUE TITLE
Version 0.9.1 installation 

### ISSUE THREAD

**Issue by SBanuprathap** [xtreme1-io/xtreme1#256]
Hello Team,

If i try to install the latest version 0.9.1 we facing the issue as below.
![V0 9 1 Issue](https://github.com/xtreme1-io/xtreme1/assets/170914285/128781c0-ecdc-45da-a215-9a02f61b5e3a)
I have attached image for your refence. Can you please help me with the issue.

**Comment by jaggerwang** [comment]
Can you provide an more clear picture or some error text?

**Comment by SBanuprathap** [comment]
> Can you provide an more clear picture or some error text?
 please find the error comments below
 
minio-1                     | minio 04:14:51.06 INFO  ==> ** Starting MinIO **
minio-1                     |
minio-1                     |  You are running an older version of MinIO released 2 years ago
minio-1                     |  Update: Run `mc admin update`
minio-1                     |
minio-1                     |
mysql-1                     | 2024-05-29T04:14:53.812278Z 3 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
minio-1                     | MinIO Object Storage Server
minio-1                     | Copyright: 2015-2022 MinIO, Inc.
minio-1                     | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-1                     | Version: DEVELOPMENT.2022-09-01T23-53-36Z (go1.18 linux/amd64)
minio-1                     |
minio-1                     | Status:         1 Online, 0 Offline.
minio-1                     | API: http://localhost:9000
minio-1                     | Console: http://172.18.0.3:9001 http://127.0.0.1:9001
minio-1                     |
minio-1                     | Documentation: https://docs.min.io
mysql-1                     | 2024-05-29T04:15:03.869584Z 4 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1                     | 2024-05-29T04:15:13.943613Z 5 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1                     | 2024-05-29T04:15:23.988936Z 6 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1                     | 2024-05-29T04:15:34.501943Z 7 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container xtreme1-091-mysql-1 is unhealthy

C:\Users\name\Videos\xtreme1-0.9.1\xtreme1-0.9.1>

**Comment by SBanuprathap** [comment]
please find the error comments below

minio-1 | minio 04:14:51.06 INFO ==> ** Starting MinIO **
minio-1 |
minio-1 | You are running an older version of MinIO released 2 years ago
minio-1 | Update: Run mc admin update
minio-1 |
minio-1 |
mysql-1 | 2024-05-29T04:14:53.812278Z 3 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
minio-1 | MinIO Object Storage Server
minio-1 | Copyright: 2015-2022 MinIO, Inc.
minio-1 | License: GNU AGPLv3 https://www.gnu.org/licenses/agpl-3.0.html
minio-1 | Version: DEVELOPMENT.2022-09-01T23-53-36Z (go1.18 linux/amd64)
minio-1 |
minio-1 | Status: 1 Online, 0 Offline.
minio-1 | API: http://localhost:9000/
minio-1 | Console: http://172.18.0.3:9001/ http://127.0.0.1:9001/
minio-1 |
minio-1 | Documentation: https://docs.min.io/
mysql-1 | 2024-05-29T04:15:03.869584Z 4 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1 | 2024-05-29T04:15:13.943613Z 5 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1 | 2024-05-29T04:15:23.988936Z 6 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
mysql-1 | 2024-05-29T04:15:34.501943Z 7 [Note] Access denied for user 'xtreme1'@'localhost' (using password: YES)
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container xtreme1-091-mysql-1 is unhealthy

C:\Users\name\Videos\xtreme1-0.9.1\xtreme1-0.9.1>

**Comment by jaggerwang** [comment]
It seems MySQL is not sucessfully installed, do you ever installed Xtreme1? You should unintall the previous one first, run `docker compose down -v` to delete all containers and volumes, it will clear all data, please backup first!
