### ISSUE TITLE
Pointcloud annotation question

### ISSUE THREAD

**Issue by ElodieShan** [xtreme1-io/xtreme1#258]
Thank you very much for your work, it is a great platform. However, when using the cloud platform, I found that the color rendering of point cloud data can only use the z-coordinate attribute or fixed color. Is there a way to use custom attributes to render colors on the cloud platform, such as intensity, etc.

**Comment by guhaomine** [comment]
Cloud platform support intensity if your pcd file has intensity field.
![image](https://github.com/xtreme1-io/xtreme1/assets/45654441/c3bbf07e-4772-40b9-b624-6ebba7b08b78)
