### ISSUE TITLE
how to configure for fisheye cameras

### ISSUE THREAD

**Issue by song-GAO-1992** [xtreme1-io/xtreme1#259]
Hi, thanks for your great work firstly.
Now I came up to a question that can not projects points to image correctly in lidar fusion task. I have configured "distortionK" & "distortionP" in datasets while this only works for pinhole model. Could you give some advice? 
Tks

**Comment by guhaomine** [comment]
If there is only radial distortion parameter, you can only fill in distortionK, and if there is no tangential distortion, distortionP is not needed.

**Comment by song-GAO-1992** [comment]
I checked the results after uploaded distortionK and found it only works on the cuboid. Is that right?

**Comment by guhaomine** [comment]
Polygon and polyline are also supported
