### ISSUE TITLE
How to copy and paste object to a different location in the same frame

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#262]
I have checked the copy one frame forward/backward function in the bottom toolbar to copy an object to another frame.
https://github.com/xtreme1-io/xtreme1/blob/main/frontend/pc-tool/src/components/TimeLine/toolbar.vue

Is there any way to copy it to a different location in the same frame?

if you have no plan yet but need, maybe I can contribute?

**Comment by jaggerwang** [comment]
Right now this feature is not supported in open source version, but cloud version support this feature.
