### ISSUE TITLE
How to perform semantic segmentation tasks?

### ISSUE THREAD

**Issue by StreetXBoy** [xtreme1-io/xtreme1#265]
May I ask if the front-end code for semantic segmentation is open-source? We would like to use the feature of semantic segmentation

**Comment by jaggerwang** [comment]
It's not available in open source edition right now, you can use our free cloud edition.

**Comment by gwy0o0** [comment]
> It's not available in open source edition right now, you can use our free cloud edition.

Excuse me, how to semantically segment lane lines and traffic objects? Thank you for your answer.
