### ISSUE TITLE
build front

### ISSUE THREAD

**Issue by weishan-990613** [xtreme1-io/xtreme1#266]
![667ace6d683fac5dfba3ea91e6ac6c3](https://github.com/xtreme1-io/xtreme1/assets/72741824/d92b76cb-8a50-4c6c-a525-f3b967b53398)
Hello, I'm trying to build front, but I'm stuck here: => [build 4/7] RUN --mount=type=cache,target=main/node_modules cd main && npm install && npm run build

**Comment by weishan-990613** [comment]
Or I would like to ask, besides changing the source code compilation, is there any other way to support Chinese translation?

**Comment by jaggerwang** [comment]
If you stuck on npm build, you should check your network connection, and use some mirror repo that you can access. Right now, it not support internationalization。

**Comment by weishan-990613** [comment]
Thank you for your answer. If I modify EN_US under localeSetting.ts to ZH_CN, can I change the interface to Chinese?

**Comment by jaggerwang** [comment]
No, because you dont't have any message translation files, this will only change the UI component's language, not the business content.

**Comment by weishan-990613** [comment]
Thanks~
