### ISSUE TITLE
To get 2D BBox in addition to 2D cuboids

### ISSUE THREAD

**Issue by arminiusresistance** [xtreme1-io/xtreme1#267]
the tools gives 2D cuboid as a sensor fusion  tool, but how about 2D bounding box, does it also provide it? I would like to contribute to this project and add semantic segmentation as well.

**Comment by guhaomine** [comment]
![image](https://github.com/xtreme1-io/xtreme1/assets/45654441/1f1c524b-21e9-43ed-b30f-02edca678c11)
We support rectangle and bbox like this.
