### ISSUE TITLE
Lombok version isssue

### ISSUE THREAD

**Issue by q5228** [xtreme1-io/xtreme1#271]
![image](https://github.com/user-attachments/assets/f054369c-2134-4297-9b03-17bb72e2ed16)
When I try to setup the backend environment, IDEA reporting the issue "SuperBuilder" can not found,could you help to check which lombok is the suitable version?

**Comment by jaggerwang** [comment]
The version of lombok is defined in [pom.xml](https://github.com/xtreme1-io/xtreme1/blob/main/backend/pom.xml), which will be auto decided by Spring Framework. You can reference this similar [question](https://stackoverflow.com/questions/59626796/lomboks-superbuilder-error-java-cannot-find-symbol) on Stackoverflow.
