### ISSUE TITLE
When I deploy locally, there are 401 errors in login and registration requests

### ISSUE THREAD

**Issue by mesakas** [xtreme1-io/xtreme1#272]
I started the main in Frontend using Vite locally, and then started Backend. However, when I logged in and registered, I encountered a 401 error:

![Screenshot from 2024-07-26 09-46-54](https://github.com/user-attachments/assets/9e0f5c38-b452-4289-8fab-4515e9288644)

which I believe may be related to Spring Security and Jwt

**Comment by mesakas** [comment]
When I first send a request, springboot will display the following message:

2024-07-26 09:45:56.158  INFO 2423962 --- [0.0-8080-exec-1] o.apache.tomcat.util.http.parser.Cookie  : A cookie header was received [mp_G6j7j#$&YOy9&p(s2b@v53^)38E!cG49_mixpanel=%7B%22distinct_id%22%3A%20%22190e92a0790102e-0355e28e8fc692-12462c6f-384000-190e92a07912450%22%2C%22%24device_id%22%3A%20%22190e92a0790102e-0355e28e8fc692-12462c6f-384000-190e92a07912450%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D;] that contained an invalid cookie. That cookie will be ignored.



![image](https://github.com/user-attachments/assets/9b11b25b-5a81-4a4f-a9b1-b18fbf7abc8b)

**Comment by jaggerwang** [comment]
It seems that you already have an invalid jwt token in your browser's local storage, can you clear site data and try again. If you are using Chrome, you can find the "Clear site data" button in "DevTools -> Application -> Storage" page.

**Comment by mesakas** [comment]
I have tried, but the same error still occurred..

![image](https://github.com/user-attachments/assets/2440b60e-c16e-4e54-a853-85d50c43ce46)

![image](https://github.com/user-attachments/assets/d2f0d608-ea16-4f92-a185-0b908d3e2bc3)

![image](https://github.com/user-attachments/assets/64b0ccd0-fe42-44fe-8522-5458997f78b3)

![image](https://github.com/user-attachments/assets/db219d08-c420-4ac7-aee3-91a9bad6c41b)

**Comment by mesakas** [comment]
I have found the reason, there is an error in the configuration in Vite.
In `vite.config.ts` code:

```ts
    // 60 lines
    server: {
      // Listening on all local IPs
      host: true,
      port: VITE_PORT,
      // Load proxy configuration from .env
      proxy: createProxy(VITE_PROXY),
    }
```

and in `.env.development` file:
```
VITE_PROXY = [
["/api","http://localhost:8080/"],
["/upload","http://localhost:8080"]
]
```



just change `vite.config.ts`:
``` ts
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, '')
        },
        '/upload': {
          target: 'http://localhost:8080',
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/upload/, '')
        }
      },
```

But this may not be an elegant solution, writing a separate dev configuration file would be better.

**Comment by mesakas** [comment]
Now there is a new problem, when I use the/upload API, there is a cors issue again, and the front-end cannot connect to Minio for data transmission. The above solution cannot completely solve the problem.

![image](https://github.com/user-attachments/assets/1a0a5b6d-0f56-40e4-a7f8-a007818a52f6)
![image](https://github.com/user-attachments/assets/0256e6e2-1881-4a94-881a-1246714daf6b)

**Comment by mesakas** [comment]
I started Minio and made the necessary configurations, but it doesn't seem to have any effect.

![image](https://github.com/user-attachments/assets/ba861e13-3edc-4d63-91a4-7b2ac9f230b3)

**Comment by jaggerwang** [comment]
To avoid CORS issue when access MinIO issue, you should proxy MinIO service in your local frontend developing server, like the [configuration of Nginx](https://github.com/xtreme1-io/xtreme1/blob/main/deploy/nginx/conf.d/default.conf).

![image](https://github.com/user-attachments/assets/961a4b13-908f-47b4-b09a-5e88accdf169)
https://github.com/xtreme1-io/xtreme1/blob/main/deploy/nginx/conf.d/default.conf

**Comment by mesakas** [comment]
> To avoid CORS issue when access MinIO issue, you should proxy MinIO service in your local frontend developing server, like the [configuration of Nginx](https://github.com/xtreme1-io/xtreme1/blob/main/deploy/nginx/conf.d/default.conf).
> 
> ![image](https://private-user-images.githubusercontent.com/1255011/352890693-961a4b13-908f-47b4-b09a-5e88accdf169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjI1ODcsIm5iZiI6MTcyMjIyMjI4NywicGF0aCI6Ii8xMjU1MDExLzM1Mjg5MDY5My05NjFhNGIxMy05MDhmLTQ3YjQtYjA5YS01ZTg4YWNjZGYxNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDMwNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRiMThjZWM0ODE2NWI0NTBiNzE3ZGU2NzY4MzU4MjY3MjhiOTJiYjY1YTg0ZGIyZTg1Y2MyMGE1MjliY2Q0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W_eUA5lk7Wp5uqkKJgcVH97rHChl5lesvcRiQdvblJ0) https://github.com/xtreme1-io/xtreme1/blob/main/deploy/nginx/conf.d/default.conf

Thank you for your response!

Did you also use nginx as a proxy during development? Isn't it directly using Vite to request the built-in Tomcat in SpringBoot?

How should I use nginx as a proxy for development?

**Comment by jaggerwang** [comment]
We have a dedicated deveopment  environment for integration development, which use nginx as reverse proxy. After backend and frontend developers each indepently finished their part of work, they can do integration work in this environment. But you still can configure your local frontend development server to proxy minio service if it can do they same work of nginx.

**Comment by mesakas** [comment]
> We have a dedicated deveopment environment for integration development, which use nginx as reverse proxy. After backend and frontend developers each indepently finished their part of work, they can do integration work in this environment. But you still can configure your local frontend development server to proxy minio service if it can do they same work of nginx.
Thank you for your response!

**Comment by Fungungun** [comment]
> I have found the reason, there is an error in the configuration in Vite. In `vite.config.ts` code:
> 
> ```ts
>     // 60 lines
>     server: {
>       // Listening on all local IPs
>       host: true,
>       port: VITE_PORT,
>       // Load proxy configuration from .env
>       proxy: createProxy(VITE_PROXY),
>     }
> ```
> 
> and in `.env.development` file:
> 
> ```
> VITE_PROXY = [
> ["/api","http://localhost:8080/"],
> ["/upload","http://localhost:8080"]
> ]
> ```
> 
> To fix this issue, simply change the `vite.config.ts` file:
> 
> ```ts
>       proxy: {
>         '/api': {
>           target: 'http://localhost:8080',
>           changeOrigin: true,
>           rewrite: (path) => path.replace(/^\/api/, '')
>         },
>         '/upload': {
>           target: 'http://localhost:8080',
>           changeOrigin: true,
>           rewrite: (path) => path.replace(/^\/upload/, '')
>         }
>       },
> ```
> 
> But this may not be an elegant solution, writing a separate dev configuration file would be better.

@mesakas hi I tried this but still cannot connect to the backend /api  and keep getting `Error: connect ECONNREFUSED ::1:8080`  any thoughs ?


THanks

**Comment by mesakas** [comment]
> > I have found the reason, there is an error in the configuration in Vite. In `vite.config.ts` code:
> > ```ts
> >     // 60 lines
> >     server: {
> >       // Listening on all local IPs
> >       host: true,
> >       port: VITE_PORT,
> >       // Load proxy configuration from .env
> >       proxy: createProxy(VITE_PROXY),
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in `.env.development` file:
> > ```
> > VITE_PROXY = [
> > ["/api","http://localhost:8080/"],
> > ["/upload","http://localhost:8080"]
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To fix this issue, simply change the `vite.config.ts` file:
> > ```ts
> >       proxy: {
> >         '/api': {
> >           target: 'http://localhost:8080',
> >           changeOrigin: true,
> >           rewrite: (path) => path.replace(/^\/api/, '')
> >         },
> >         '/upload': {
> >           target: 'http://localhost:8080',
> >           changeOrigin: true,
> >           rewrite: (path) => path.replace(/^\/upload/, '')
> >         }
> >       },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But this may not be an elegant solution, writing a separate dev configuration file would be better.
> 
> @mesakas hi I tried this but still cannot connect to the backend /api and keep getting `Error: connect ECONNREFUSED ::1:8080` any thoughs ?
> 
> THanks

I haven't looked further into this issue, but one approach that comes to mind is to configure Nginx as a proxy, which might help resolve the cross-origin problem.
