### ISSUE TITLE
questions for local development

### ISSUE THREAD

**Issue by Fungungun** [xtreme1-io/xtreme1#273]
Hi

Thanks for sharing your great work. I am trying to make some small changes to the tool but no luck. 

Here's what I did

* I ran all the modules using docker compose except frontend on which i want to make changes

*  `npm run dev`  in folder frontend/main/ and also change the proxy in `vite.config.ts` and `.env.development`

![image](https://github.com/user-attachments/assets/d2d8a5d1-c2c5-42e1-be6f-efcf873f0332)

* i tried proxy /api to different urls including localhost:8290 localhost:8190 localhost:8080 but I keep getting `Error: connect ECONNREFUSED ::1:8080`

![image](https://github.com/user-attachments/assets/fa0ffbc2-5b42-4d6f-904a-6c4d1b2af090)

Could you please help point out what i have missed in configuration ?

Thanks again for your great work

**Comment by jaggerwang** [comment]
First, make sure you can connect the nginx proxyed backend service at address `http://localhost:8190` using curl or similar tools. You should not directly connect to the backend service in frontend, as the `/api` prefix is added by nginx and it will be removed when transer request to backend service.

**Comment by Fungungun** [comment]
> First, make sure you can connect the nginx proxyed backend service at address `http://localhost:8190` using curl or similar tools. You should not directly connect to the backend service in frontend, as the `/api` prefix is added by nginx and it will be removed when transer request to backend service.

Hi jagger

Thanks for your reply.  

I tried to curl the backend service and it seems to function normally. Plase check below

Could you tell me how to configure my proxies so that I can develop the frontend module locally ?

Thanks again

------
curl -f http://localhost:8290/actuator/health
{"code":"OK","message":"","data":{"status":"UP","groups":["liveness","readiness"]}}% 
![image](https://github.com/user-attachments/assets/c342cc71-5790-42dc-9ead-16f00ff48d89)

**Comment by jaggerwang** [comment]
Like I previously said, you should use the port of nginx and add `/api` prefix to the path, like `http://localhost:8290/api/actuator/health`. Port 8290 is the port of backend servie, you should not access backend service directly in frontend.

**Comment by Fungungun** [comment]
> Like I previously said, you should use the port of nginx and add `/api` prefix to the path, like `http://localhost:8290/api/actuator/health`. Port 8290 is the port of backend servie, you should not access backend service directly in frontend.

thanks and sorry for bothering again, I have coufigured like below but I still got 

```1:41:01 PM [vite] http proxy error:
Error: connect ECONNREFUSED ::1:8190
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)```

![image](https://github.com/user-attachments/assets/eee6f591-1b89-4114-8c10-fdd76327ffc7)

**Comment by jaggerwang** [comment]
Try to change localhost to 127.0.0.1, it seems that there have a bug of vite, https://github.com/vitejs/vite/discussions/7620.

**Comment by Fungungun** [comment]
> Try to change localhost to 127.0.0.1, it seems that there have a bug of vite, [vitejs/vite#7620](https://github.com/vitejs/vite/discussions/7620).

thanks a lot problem solved. It turns out this is a issue related to IPv4 and IPv6 local address. 


Thanks again
