### ISSUE TITLE
ID generation issues with image-tool Copy backId (compared to pc-tool)

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#274]
**Describe the bug**
In the copy function of image-tool, if the data has a backId, it is copied together and the copy is not saved in the DB.

**To Reproduce**
1. Select box with backId.
2. Copy another frame.
3. Click Save.
4. Refresh browser and then Find box.

**Expected behavior**
I think I should be able to find the box even after a refresh.

comparing with pc-tool, I can see that the part that handles backId is missing.

[image-tool](https://github.com/xtreme1-io/xtreme1/blob/14961eecc61349927c2d6743df36302ae9a50410/frontend/image-tool/src/package/image-editor/utils/data.ts#L72)
```ts
        const newObject = annotate.cloneThisShape();
        newObject.userData.resultStatus = Const.Copied;
        addOption.objects.push(newObject);
```

[pc-tool](https://github.com/xtreme1-io/xtreme1/blob/14961eecc61349927c2d6743df36302ae9a50410/frontend/pc-tool/src/packages/pc-editor/utils/data.ts#L65)
```ts
      newUserData.backId = '';
```

**Desktop (please complete the following information):**
- OS: Mac
- Browser Chrome
- Version 124.0.6367.93

**Additional context**
Thank you all for your contributions and great features. They are always appreciated.
If there are no objections, would it be alright if I contribute to this issue?

**Comment by jaggerwang** [comment]
Thanks for your contribution!
