### ISSUE TITLE
Prevent unlock before saveObject completion during immediate submission

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#280]
**Describe the bug**
When submitting data immediately using 'Submit' Button, the unlock function is executed before saveObject completes, causing an error if saveObject takes longer to finish.

**To Reproduce**
1. Go to the `pc-tool annotate` page
2. Click to "Submit" button of header immediately after new box creation
3. Observe that unlock is called before `editor.saveObject` finishes
4. Upon reconnecting, See that the save failed.

**Expected behavior**
The saveObject function should complete before unlock is called, ensuring that all data is properly saved before unlocking.

[useHeader.ts](https://github.com/xtreme1-io/xtreme1/blob/main/frontend/pc-tool/src/components/Header/useHeader.ts)

**AS-IS**

```ts
editor.saveObject(frames, true);
await api.submitData(seriesFrameData ?? '');
// await updateDataStatus(frames);
unlockData();
bsState.submitting = false;
return;
```

**TO-BE**

```ts
await editor.saveObject(frames, true);
await api.submitData(seriesFrameData ?? '');
// await updateDataStatus(frames);
unlockData();
bsState.submitting = false;
return;
```

**Desktop (please complete the following information):**
OS: Mac
Browser Chrome
Version 124.0.6367.93

**Additional context**
Thank you all for your contributions and great features. They are always appreciated.

**Comment by jaggerwang** [comment]
PR merged, thanks for your contribution!
