### ISSUE TITLE
Proposal to Change Frontend and Backend Related Language in CONTRIBUTING.md

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#288]
Hello,

After reading [CONTRIBUTING.md](https://github.com/xtreme1-io/xtreme1/blob/main/CONTRIBUTING.md), I think to changing the project's frontend (FE) and backend (BE) Related Language.

**AS-IS**
| Component Name | Component Description | Related Language |
|----------------|-----------------------|------------------|
| [Frontend (FE)](https://github.com/xtreme1-io/xtreme1) | Xtreme1 web ui | Java |
| [Backend (BE)](https://github.com/xtreme1-io/xtreme1)  | Xtreme1 api service | JavaScript, TypeScript, HTML, CSS |
| [Docs](https://github.com/xtreme1-io/docs)        | Xtreme1 documents | Markdown |

**TO-BE**
| Component Name | Component Description | Related Language |
|----------------|-----------------------|------------------|
| [Frontend (FE)](https://github.com/xtreme1-io/xtreme1) | Xtreme1 web ui | JavaScript, TypeScript, HTML, CSS |
| [Backend (BE)](https://github.com/xtreme1-io/xtreme1)  | Xtreme1 api service | Java |
| [Docs](https://github.com/xtreme1-io/docs)        | Xtreme1 documents | Markdown |

Thank you all for your contributions and great features. They are always appreciated.

**Comment by jaggerwang** [comment]
Fixed, thanks for your feedback!
