### ISSUE TITLE
about lidar od model

### ISSUE THREAD

**Issue by yvanwy** [xtreme1-io/xtreme1#291]
It seems that the lidar detection model deployed in the basic.ai website is not consistent with the open source code? I found that the test results were inconsistent
![image](https://github.com/user-attachments/assets/635e9c44-0436-4c91-a363-60d0ec010a65)
![image](https://github.com/user-attachments/assets/ce9247cf-486c-4f78-802b-568da35d68bf)

**Comment by jaggerwang** [comment]
Yes, the open source version of the model is not fully compatible with the Cloud version.
