### ISSUE TITLE
Are you using "loadMax" for performance?

### ISSUE THREAD

**Issue by seungdeok** [xtreme1-io/xtreme1#293]
Are you using `loadMax` for performance in the code below?
```
export default class DataResource {
    loadMax: number = 500;
    ...
}
```

<br />

Code using `loadMax`.

https://github.com/xtreme1-io/xtreme1/blob/2959792b11c7c7c1426dd4dbe208249743a4c35a/frontend/pc-tool/src/packages/pc-editor/common/DataResource.ts#L207-L208

https://github.com/xtreme1-io/xtreme1/blob/2959792b11c7c7c1426dd4dbe208249743a4c35a/frontend/image-tool/src/package/image-editor/common/ResourceManager/index.ts#L6-L11

Thank you all for your contributions and great features. They are always appreciated.

**Comment by guhaomine** [comment]
You are right. When the size loaded into memory exceeds loadMax, the earliest loaded point cloud data will be released.

**Comment by seungdeok** [comment]
Thanks reply!
