### ISSUE TITLE
Default user `admin` can't be login

### ISSUE THREAD

**Issue by Ox0400** [xtreme1-io/xtreme1#296]
Default user `admin` cant be login, because FE raise a verify failed error that's not email format when deploy on local.

The solution is to change the default admin user to email format.

```
mysql -u root -p -d xtreme1

update user set username = 'admin@admin.com' where username = 'admin';

```

Then login with email: `admin@admin.com` and password `root@123`.

**Comment by jaggerwang** [comment]
Admin is only used to initialize data, only for internal use, you should register your own account to log in.
