### ISSUE TITLE
Failed to upload point cloud fusion data with labels

### ISSUE THREAD

**Issue by USTBhyh** [xtreme1-io/xtreme1#304]
Hello, how do I import point cloud fusion data with initial annotations? I'm now packing and uploading the file structure as shown in the image, but the result is that the initial annotations don't show up on the platform.
您好，请问我如何导入有初始标注的点云融合数据呢？我现在按照如图所示的文件结构进行打包并上传，但结果是初始的标注没法显示在平台上。

The specific compressed file is as follows（具体压缩包如下zip文件）：
[LiDAR_Fusion_test.zip](https://github.com/user-attachments/files/18051303/LiDAR_Fusion_test.zip)
The file structure is shown in the image（文件结构如图所示）：
![image](https://github.com/user-attachments/assets/cddc5999-f16f-4f8d-b31d-a4294c9b38e1)

Result: The data is successfully imported, but there is no initial labeling.（结果：导入数据成功，但是没有初始标注。）

**Comment by USTBhyh** [comment]
Results Supplement（结果补充）：
![image](https://github.com/user-attachments/assets/3ee4f196-c892-444e-92ca-66f8403b9861)
![image](https://github.com/user-attachments/assets/cc64c31d-1db6-42ff-bacd-df7e15db4dc0)

**Comment by llz666ha** [comment]
Hello, can we upload the annotation data without id and trackId? The sample data has these attributes, but my annotation data does not have so many attributes.
sample:
{
                "id": "85c29447-7e88-4b5b-b34f-0eae06f59842",
                "type": "3D_BOX",
                "trackId": "0a945822-ee22-41a6-b929-fe12079d77a4",
                "trackName": "45",
                "classValues": null,
                "group": null,
                "contour": {
                    "center3D": {
                        "x": 61.724,
                        "y": 62.386,
                        "z": 0.272
                    },
                    "maxDistance": 33.847,
                    "minDistance": 29.63,
                    "pointN": 11,
                    "rotation3D": {
                        "x": 0,
                        "y": 0,
                        "z": 0.79
                    },
                    "size3D": {
                        "x": 4.33,
                        "y": 1.986,
                        "z": 1.83
                    }
                },
                "modelConfidence": 0.521,
                "modelClass": "Car",
                "classId": null,
                "className": null,
                "classNumber": null,
                "classVersion": null,
                "isValid": null,
                "note": null,
                "start": null,
                "end": null,
                "createdAt": 1706151463000,
                "createdBy": 90014
            }

**Comment by Zhao-Qihao** [comment]
Hi, have you solved this problem? I also encountered the same problem
