### ISSUE TITLE
Export class names

### ISSUE THREAD

**Issue by AndyFrancesco29** [xtreme1-io/xtreme1#72]
Hi, I am using the website version for annotating lidar point. When I export the result file from the website, I cannot find the class label for each bounding box in the result json file. For example, for the sample data, I got the following content:

`[{"version":"1.0","dataId":33540037,"sourceId":30930,"sourceType":"DATA_FLOW","sourceName":"Without Task","validity":"VALID","classificationValues":[],"objects":[{"id":"f0c0e30b-5b9a-4c50-9a21-59eecda55a6e","type":"3D_BOX","trackId":"NpFkgZwEuid1z0x1","trackName":"1","classValues":[{"alias":"","id":"f7434cfd-a542-4e00-825d-cd4ed0b76e4e","isLeaf":true,"name":"","value":"High"},{"alias":"","id":"0250dfc6-f0b5-49f7-8809-7442ec1293a9","isLeaf":true,"name":"","value":"No"}],"contour":{"center3D":{"x":0.07479472138966892,"y":5.685984817386404,"z":0.7350000000000002},"pointN":1660,"points":[],"rotation3D":{"x":0,"y":0,"z":0.7830466862070613},"size3D":{"x":4.115060429478478,"y":1.9631255795928428,"z":1.4900000000000042},"viewIndex":0},"modelConfidence":null,"modelClass":""},{"id":"ec77bf46-df89-4f38-a09a-3bb1ecd1d96b","type":"3D_BOX","trackId":"n2Q5TgmrkuB0ceLZ","trackName":"2","classValues":[{"alias":"","id":"0250dfc6-f0b5-49f7-8809-7442ec1293a9","isLeaf":true,"name":"","value":"Yes"},{"alias":"","id":"f7434cfd-a542-4e00-825d-cd4ed0b76e4e","isLeaf":true,"name":"","value":"Medium"}],"contour":{"center3D":{"x":25.86569116182311,"y":1.510761637851699,"z":0.617681331542546},"pointN":1751,"points":[],"rotation3D":{"x":0,"y":0,"z":-0.9403950741664222},"size3D":{"x":6.361173403725293,"y":2.372192347521158,"z":2.0680939598347616},"viewIndex":0},"modelConfidence":null,"modelClass":""}]}]`

However, for the class values, I could only find the content for the class attribute, but I cannot find the name such as cars, vans, trucks. Can you help me with this? Thank you very much.

**Comment by nicozhan** [comment]
Hi Andy,

Thanks for using our platform.
It seems this is a bug with the v0.6 update. We will get back to you asap!

**Comment by jaggerwang** [comment]
Right now only class values are exported, not including class name, we will add it in next v0.5.5, which will be released at next week. Thanks for you reporting.

**Comment by AndyFrancesco29** [comment]
Thank you very much for your reply! May I ask if the version is updated, my current annotation on the website can still be used or not?

**Comment by nicozhan** [comment]
This output issue was fixed. Please try again to export your annotation again?

Let me know if it works or not?

**Comment by AndyFrancesco29** [comment]
The problem has been solved. Thank you very much!
