### ISSUE TITLE
Extrinsic parameters for the annotation tool

### ISSUE THREAD

**Issue by AndyFrancesco29** [xtreme1-io/xtreme1#80]
Hi,

I am using the online version of your annotation tool and I would like to ask how did you calibrate the extrinsic parameter for camera and lidar? I have used the dataset from Dair-V2X (https://thudair.baai.ac.cn/index) and the calibration seems not quite accurate. Could you suggest some useful tools or methods for extrinsic parameter calibration? Thank you very much.

**Comment by nicozhan** [comment]
Check out this docs:
https://docs.xtreme1.io/xtreme1-docs/product-guides/lidar-annotation-tool/coordinate-system

If you still have question, please let me know.
