### ISSUE TITLE
Pcd/img frame can not be operated after removing users.

### ISSUE THREAD

**Issue by antaressgzz** [xtreme1-io/xtreme1#84]
I use the docker version. I find that if a user is removed when some pcd/image frames are occupied by this user, then these pcd/img frames cannot be annotated and removed in the dataset by others.

**To Reproduce**
1. Register 2 users A and B.
2. User A is annotating frame F in a dataset D.
3. User B remove user A.

**Expected behavior**
User B cannot annotate and remove frame F in a dataset D, though this frame is not (shown to be) occupied by others.

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser edge

**Comment by jaggerwang** [comment]
Thanks for your feedback, right now when removing user the data/frames locked by this user are not unlocked, we've already have a plan to fix this problem. 

You can use the following sql to unlock the data/frames locked by this user (replace `<email>` to the removed user's email):
```sql
DELETE FROM data_annotation_record WHERE created_by in(SELECT id FROM `user` WHERE username='<email>');
DELETE FROM data_edit WHERE created_by in(SELECT id FROM `user` WHERE username='zhujunhao@basicfinder.com');
```

**Comment by butterflyzh** [comment]
Fixed in dev branch.
