### ISSUE TITLE
Upload fusion dataset

### ISSUE THREAD

**Issue by nicozhan** [xtreme1-io/xtreme1#87]
(nuscenes dataset) Failed to upload dataset on open source version.

**Comment by nicozhan** [comment]
Fix.
It is expected that when uploading Lidar Fusion datasets, they can be displayed without a camera config file.

**Comment by MoscatoMao** [comment]
I have a same question,  what is the format of camera config file

**Comment by Ragavi1209** [comment]
You can refer this
https://docs.basic.ai/lidar/Coordinate-System#coordinate-system-1
