### ISSUE TITLE
login with docker version fails if the email-ID contains DOT

### ISSUE THREAD

**Issue by Xcrater** [xtreme1-io/xtreme1#88]
Docker containers are running successfully
![image](https://user-images.githubusercontent.com/8291682/220666507-f935c778-ba4e-4b33-8b6e-141b937856f9.png)
Looks like there is a bug at the backend if the email-ID contains "." in it the login fails.

![image](https://user-images.githubusercontent.com/8291682/220668742-5f6f16b6-d3b0-454a-ad05-e02adaada6a1.png)
![image](https://user-images.githubusercontent.com/8291682/220668780-d89495fc-42cc-45d1-b7ba-2d48c977f837.png)

**Comment by jaggerwang** [comment]
Thanks for your feedback! We will remove this limit as quickly as possible.

**Comment by nicozhan** [comment]
This issue has been fixed!
