### ISSUE TITLE
 request for extrinsic LiDAR-image calibration tool

### ISSUE THREAD

**Issue by Xcrater** [xtreme1-io/xtreme1#89]
It would be great to have an inbuild robust extrinsic calibration tool, the extrinsic value can be embedded as an attribute for each object ID's

Example:
[
    {
        "id": 0,
        "name": "pc0",
        "type": "pointcloud",
        "extrinsics": {
            "location": [
                -0.7956064878711493,
                0.06994663796442704,
                0.07554082295382114
            ],
            "rotation": [
                0.06168062793771913,
                0.01200528651139976,
                -0.26920656196175347
            ]
        }
    },
    {
        "id": 1,
        "name": "image2",
        "type": "image",
        "intrinsics": {
            "focal": [
                721.5377197265625,
                721.5377197265625
            ],
            "center": [
                609.559326171875,
                172.85400390625
            ],
            "skew": 0,
            "radial": null,
            "tangential": null
        },
        "extrinsics": {
            "location": [
                -0.0027968167666705956,
                -0.0751087909738869,
                -0.27213280776889376
            ],
            "rotation": [
                0.011902515224334161,
                -1.5603441219160237,
                1.548328901848571
            ]
        }
    },
    {
        "id": 2,
        "name": "image3",
        "type": "image_3d",
        "intrinsics": {
            "focal": [
                721.5377197265625,
                721.5377197265625
            ],
            "center": [
                609.559326171875,
                172.85400390625
            ],
            "skew": 0,
            "radial": null,
            "tangential": null
        },
        "extrinsics": {
            "location": [
                -0.5327253937721252,
                0.0,
                0.0
            ],
            "rotation": [
                -1.5723664220969806,
                0.07224191126404556,
                -1.8406363281435645
            ]
        }
    }
]

**Comment by nicozhan** [comment]
We'll let you know as soon as it launches.

**Comment by nicozhan** [comment]
We'll let you know as soon as it launches.
