### ISSUE TITLE
No Docker Support for /linux/arm64/v8 (OSX MacBook M1/M2 chipset)

### ISSUE THREAD

**Issue by mptil** [xtreme1-io/xtreme1#96]
**Is your feature request related to a problem? Please describe.**
Trying to get this running on docker on newer Mac builds. Doesn't appear to be a docker setup for my chipset

**Describe the solution you'd like**
Any chance you can build your platform for the M1 chipset and publish the container with the correct dependencies?

**Describe alternatives you've considered**
I'll probably drop this on an NVIDIA Jetson appliance so I can have a look, but if I am going to use it with any regularity, it will be on a Mac. Probably not the only Mac based prospective customer out there.

**Additional context**
None

**Comment by nicozhan** [comment]
## Running docker images on ARM architecture machines 
Please note that certain Docker images, including MySQL, may not be compatible with the ARM architecture. In case your computer is based on an ARM CPU (e.g. Apple M1), you can create a Docker Compose override file called `docker-compose.override.yml` and include the following content. While this method uses QEMU emulation to enforce the use of the ARM64 image on the ARM64 platform, it may impact performance.
```
services:
  mysql:
    platform: linux/amd64
```

I just updated it on docs:
https://docs.xtreme1.io/xtreme1-docs/

**Comment by nicozhan** [comment]
This is not yet in our roadmap.
You can try this feature in the [cloud version](https://app.basic.ai/).
