### ISSUE TITLE
Can't see imported 3D point cloud in the online tool

### ISSUE THREAD

**Issue by boazMgm** [xtreme1-io/xtreme1#99]
Hi,
when trying to view the imported dataset (Lidar PCD file) I see this image in the viewer:
![image](https://user-images.githubusercontent.com/89138398/225015532-eddd0ba2-2d8b-4d54-af6b-63f913565cc9.png)

What may be the reason?
Thanks a lot

**Comment by nicozhan** [comment]
Hi @boazMgm!

It looks like the format is correct, but it may be due to the data coordinate reason. Or data contain too less points, e.g. 3D Radar data.

Can your data be displayed normally on other software (e.g. [Cloud compare](https://www.danielgm.net/cc/))?
If it is the Xtreme1 problem, can you share me your sample data here or DM me via Slack? Our engineers can help you take a look.

**Comment by boazMgm** [comment]
Hi,
Thanks a lot for your quick reply.
I will attach here part of the pcd file (there are total 14373 points in this frame)


# .PCD v3.0 - Extended
VERSION 3.0      
FIELDS x y z intensity
SIZE 8 8 8 8
TYPE F F F F
COUNT 1 1 1 1
WIDTH 14373      
HEIGHT 1      
VIEWPOINT 0 0 0 1
POINTS 14373      
DATA ascii      
HEADER_EXT_START 6      
SENSOR_TYPE VELODYNE_LIDAR      
MODE None      
TIMESTAMP 1635320299.258362      
VIEWPOINT_TYPE Host      
VIEWPOINT_HAND Right      
ALIGNED False      
HEADER_EXT_END        
3.36597 2.083739 -1.845997 3 0
49.99408 38.1681 -1.097896 20 17
26.03415 16.11671 -0.8911012 7 15
5.48787 3.780178 -1.865462 1 1
7.953963 4.923983 -1.870959 1 2
39.42415 27.15631 0 10 20
65.85187 36.44223 -0.8762011 45 18
9.758411 6.72183 -1.8435 0 3
12.53037 7.757054 -1.875841 1 4
69.207 52.83624 0.506055 40 21
14.16517 9.757313 -1.852779 1 5
17.20736 9.522501 -1.835831 3 6
39.09404 26.92892 1.104627 7 24
106.0972 58.71388 1.411691 63 22
19.44369 12.03682 -1.866826 3 7
76.57093 58.45825 2.803629 59 25
88.02935 54.49548 1.807162 63 23
22.09251 16.86658 -1.781346 3 9
25.3064 14.00449 -1.684404 4 10
25.9998 16.09545 1.245806 30 26
99.43198 61.5544 9.546658 63 28

**Comment by nicozhan** [comment]
I fixed the header lines. It works.
![image](https://user-images.githubusercontent.com/84139543/225499624-a9bbceaf-b8e0-42ca-aeb0-4a624d35261e.png)
I think you can use this header and fill in the correct `WIDTH` and `POINTS` values and try it again.

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 21
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 21
DATA ascii
```
See this file:
[point_cloud.zip](https://github.com/xtreme1-io/xtreme1/files/10986173/point_cloud.zip)

**Comment by boazMgm** [comment]
Hi,
Thanks a lot.
I have tried to upload your zip file to the online version but I get an error:
![image](https://user-images.githubusercontent.com/89138398/229431723-7027ab1c-4976-41fb-a40d-3407834bef78.png)

Do you know what may be the reason?
Thanks

**Comment by nicozhan** [comment]
Make sure using `Lidar Basic` when you create the dataset.
![image](https://user-images.githubusercontent.com/84139543/229465777-c3fd8b05-e139-41ed-be94-319a0441830c.png)

**Comment by boazMgm** [comment]
Hi,
This was my choice so I guess the root cause is somewhere else.

**Comment by boazMgm** [comment]
Hi,
Now it is showing a different and weird error:

![image](https://user-images.githubusercontent.com/89138398/229494396-ad21250e-8315-4ae7-ad65-196ed60b7713.png)

the file name is point_cloud.zip, I don't understand the problem.
Thanks

**Comment by nicozhan** [comment]
The **zip file name** can be anything.
**Folder name** must be `point_cloud`.

```
├── point_cloud
│   ├── 00.pcd
│   ├── 01.pcd
│   ├── 02.pcd
```

![image](https://user-images.githubusercontent.com/84139543/229686382-f5562eb6-11c8-460a-9be4-e2d37ec1ed38.png)

**Comment by boazMgm** [comment]
Thanks Nico!
it is now working :)

**Comment by nicozhan** [comment]
Welcome to join our [Slack channel](https://join.slack.com/t/xtreme1io/shared_invite/zt-1jhk36uzr-NpdpYXeQAEHN6rYJy5_6pg) or WeChat group to discuss further questions!
